### ISSUE TITLE
JSON Schema?

### ISSUE THREAD

**Issue by mnpenner** [loft-sh/devspace#1146]
**Is your feature request related to a problem?**  
No

**Which solution do you suggest?**  
Can you please provide a JSON Schema for `devspace.yaml`? Preferably by [contributing it to schemastore.org](https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md#json-schema). This way our IDEs will pick it up automatically and we can get completions and help when authoring this file.

**Which alternative solutions exist?**  
Pillage [the docs](https://devspace.sh/cli/docs/next/configuration/reference) and create this file by hand.

**Additional context**  
https://json-schema.org/

/kind feature

**Comment by FabianKramm** [comment]
@mnpenner thanks for opening this issue! Good idea, I will mark this as a feature

**Comment by leventogut** [comment]
@FabianKramm looks like this feature didn't happen.
It would be great for UX if we could do this.

What's your view on this?

**Comment by mnpenner** [comment]
Thanks! Was this submitted to SchemaStore.org?
