### ISSUE TITLE
Installation of devspace inside node:alpine container fails

### ISSUE THREAD

**Issue by timo-klarshift** [loft-sh/devspace#1185]
**What happened?**  
I am trying to run devspace commands inside a gitlab pipeline. For that i need to install devspace inside a docker container with image `node:alpine`. After installation when i run `devspace -h` it should usually pull some binaries and then present the help. Instead console is flooded.

**What did you expect to happen instead?**  
I am able to install devspace successful inside `node:alpine`

**How can we reproduce the bug?** (as minimally and precisely as possible)  
```bash
docker run -ti --entrypoint sh node:alpine
```

Then inside the container:

```bash
npm -g install devspace
# installation OK
devspace -h
```

Console is flooded:

```bash
sh: out of range
sh: out of range
sh: out of range
sh: out of range
sh: out of range
sh: out of range
sh: out of range
sh: out of range
sh: out of range
sh: out of range
sh: out of range
sh: out of range
sh: out of range
```

**Local Environment:**  
- docker v19
- node:alpine

/kind bug

**Comment by LukasGentele** [comment]
Not sure what is happening here but feel free to take a look at our CI image on Docker Hub: https://hub.docker.com/r/devspacesh/devspace

This is the Dockerfile which is using alpine as well: https://github.com/devspace-cloud/devspace/blob/master/Dockerfile (you should be able to just copy to install instructions from there or use the above image as base image)

**Comment by stickeegreg** [comment]
I believe this is due to Alpine / BusyBox's version of `stat` not having the long-form `--print` option.

Changing the script from
`STAT=$(stat -L -f%z "$BINARY" 2>/dev/null || stat --printf="%s" "$BINARY" 2>/dev/null)`
to
`STAT=$(stat -L -f%z "$BINARY" 2>/dev/null || stat -c"%s" "$BINARY" 2>/dev/null)`
