### ISSUE TITLE
remotePort under MacOS is not working

### ISSUE THREAD

**Issue by vorti2** [loft-sh/devspace#1309]
**What happened?**  
If I set the "remotePort" option in `devspace.yaml` like 
```
  ports:
  - imageName: app
    forward:
    - port: 3000
      remotePort: 8301
``` 
than the following statement didn't work:
```
  open:
  - url: http://localhost:8301
``` 
and my service isn't accessible under `http://localhost:8301`.

**What did you expect to happen instead?**  
Access to the service over `http://localhost:8301`.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

**Local Environment:**  
- DevSpace Version: 5.7.4
- Operating System: mac (11.1)
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: minikube ("other")
- Kubernetes Version: 
    Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
    
**Anything else we need to know?*

/kind bug

**Comment by LukasGentele** [comment]
@vorti2 The remotePort is the one inside your Kubernetes pod, so when you want to access this pod's port 8301 on localhost, you will need to use `localhost:3000` because 3000 is your local port that is being forwarded to the remote port inside your Kubernetes pod.

**Comment by vorti2** [comment]
Hi Lukas, 
thanks for the fast reply 😇.
After I reviewed my different port settings it start to work the interchange of `port`and `remotePort`
```
  ports:
  - imageName: app
    forward:
    - port: 8301
      remotePort: 3000
```
The different port settings  have confused me, sorry!
