### ISSUE TITLE
Add description for profiles

### ISSUE THREAD

**Issue by Chrislevi** [loft-sh/devspace#1312]
**Is your feature request related to a problem?**  
Not really..

**Which solution do you suggest?**  
It would be nice to have some kind of description to each profile rather than using the profiles name convention

Add description option for each item `profiles:` so whenever a new user lists all the available profiles we can describe in much detail how the profile affects the deployments.

**Which alternative solutions exist?**  
Profile name convention, it can get pretty hectic.

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
@Chrislevi thanks for opening this issue! Yes we can add this, sounds like a good idea

**Comment by FabianKramm** [comment]
@Chrislevi this was implemented in v5.7.6
