### ISSUE TITLE
Sync excludePath negating patterns do not work for download

### ISSUE THREAD

**Issue by juckerf** [loft-sh/devspace#1335]
**What happened?** 

When using an excludePath setting with negating patterns like the following, files matching the negating pattern are not synced from the container to the local filesystem:
```yaml
    excludePaths:
    - test/
    - '!test/foo'
```

**What did you expect to happen instead?**  
That files which are changed/created in test/foo are synced from the container to the local filesystem

**How can we reproduce the bug?** (as minimally and precisely as possible)  

* Take the nodejs quickstart example (https://devspace.sh/cli/docs/getting-started/initialize-project)
* `devspace init` using dockerfile and some arbitrary registry
* Add `test` to .dockerignore
* Add the following lines to excludePaths of devspace.yaml:
```yaml
    - test/
    - '!test/foo'
```
* Create directories `mkdir -p test/foo`
* Create some files `touch test/bar test/foo/bar`
* `devspace dev`
* `touch test/foo/foo` => works (from local to container)
* `kubectl exec -it CONTAINER_NAME -- touch /app/test/foo/abc` => does not work (from container to local fs)

**Local Environment:**  
- DevSpace Version: 5.8.2
- Operating System:  linux 
- Deployment method: helm 

**Kubernetes Cluster:**  
- Cloud Provider: minikube
- Kubernetes Version: 1.20.2

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@juckerf thanks for opening this issue! You are correct, this seems to be currently not working because we stop traversing sub trees on the remote side if a parent folder matches an ignore rule. We'll fix this for the next version!

**Comment by FabianKramm** [comment]
@juckerf I released v5.8.3-beta.0 which includes the fix, you can upgrade via `devspace upgrade --version=v5.8.3-beta.0`. Would be great if you could check if that fixes the issue

**Comment by juckerf** [comment]
Thanks a lot @FabianKramm and sorry for the delayed reaction. I'll give it a try as soon as possible

**Comment by juckerf** [comment]
Verified. Works with the simple setup described in the issue and works with my real world case :tada: 
Thanks!
