### ISSUE TITLE
What is the best way to handle multiple deployments running the same image? 

### ISSUE THREAD

**Issue by dtardoin** [loft-sh/devspace#1339]
**Is your feature request related to a problem?**  
Not directly, this seems to be functioning as intended. 

**Which solution do you suggest?**  
Allow multiple image definitions to use the same image. 

**Which alternative solutions exist?**  
I'm not really sure, which is why I'm asking

**Additional context**  
I'm trying to inject the restart helper into some worker k8s deployments that use the same image as my webapp.  It seemed that adding an image within devspace.yaml with the commands to be wrapped with the helper was the best way to go about achieving that, but I'm getting the error ` multiple image definitions with the same image name are not allowed`.

I can see where other people have added tags to images to overload and build them again, but then that forces me to update my helm chart to take individual image locations for each worker, which seems like not the best way to go about this. 

/kind feature

**Comment by LukasGentele** [comment]
@dtardoin Not sure if I fully understand all details here but why don't you have 1 image in `images` and then multiple `deployments` that reference this image? (Potentially overriding the entrypoint using Kuberentes pod spec `command` + `args` in each deployment). Adding multiple images triggers multiple build processes which does not seem necessary in this. Differentiating at the deployment level has the advantage that you only need to build, tag and push one image.

**Comment by dtardoin** [comment]
I was doing something wrong in my config leading to restarting apps not working.
