### ISSUE TITLE
Error updating plugin to latest when it is already on latest

### ISSUE THREAD

**Issue by fmc100** [loft-sh/devspace#1352]
**What happened?**  
Anytime I run `devspace update plugin loft` I get an error `[fatal]  no update for plugin found` rather than saying it is the latest like devspace does `[info]   Current binary is the latest version: 5.9.1`.

**What did you expect to happen instead?**  
To tell me I have latest and show me what that version is like devspace does, `[info]   Current binary is the latest version: 5.9.1`.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Install the loft plugin into devspace then run `devspace update plugin loft`, the error should come up.

**Local Environment:**  
- DevSpace Version: 5.9.1
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: 1.18.9

**Anything else we need to know?**  
I am only citing the example of the loft plugin, but I am sure other plugins have this issue as well.

/kind bug

**Comment by FabianKramm** [comment]
@fmc100 thanks for opening this issue! Sure, we can improve the message there

**Comment by fmc100** [comment]
saw this working in the latest version, thanks!
