### ISSUE TITLE
Failure when running devspace after npm install 

### ISSUE THREAD

**Issue by epierotto** [loft-sh/devspace#1363]
**What happened?**  
After installing using `npm install -g devspace` the terminal enters in an error loop if I run `devspace` command:
```
 devspace
/usr/local/bin/devspace: line 11: [: : integer expression expected
/usr/local/bin/devspace: line 11: [: : integer expression expected
/usr/local/bin/devspace: line 11: [: : integer expression expected
/usr/local/bin/devspace: line 11: [: : integer expression expected
/usr/local/bin/devspace: line 11: [: : integer expression expected
/usr/local/bin/devspace: line 11: [: : integer expression expected
/usr/local/bin/devspace: line 11: [: : integer expression expected
```
you need to ctrl + c to stop it

**What did you expect to happen instead?**  
`devspace` command to just work.

**How can we reproduce the bug?** (as minimally and precisely as possible) s 
This is the execution of `/usr/local/bin/devspace` sh script with `set -x`:
```
 devspace
++ command -v devspace
+ BINARY=/usr/local/bin/devspace
+ echo darwin20
+ grep -q 'darwin.*'
++ stat -L -f%z /usr/local/bin/devspace
+ STAT=
+ '[' '!' -f /usr/local/bin/devspace ']'
+ '[' '' -lt 10000 ']'
/usr/local/bin/devspace: line 12: [: : integer expression expected
```

stat error:
```
stat -L -f%z /usr/local/bin/devspace
stat: invalid option -- '%'
Try 'stat --help' for more information.
```

I guess that the error is triggered because I'm using `stat` from coreutils, using the `stat` command from line 8 of the script just works:
```
stat --printf="%s" "/usr/local/bin/devspace"
55371000
```

Maybe checking the version of `stat` instead of the `OSTYPE` could be a solution.

**Local Environment:**  
- DevSpace Version: `5.9.1`
- Operating System: 
  ```
       ProductName:    macOS
       ProductVersion: 11.2.2
       BuildVersion:   20D80
  ```
- sh Version:
  ```
  GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
  Copyright (C) 2007 Free Software Foundation, Inc.
  ```
- stat Version:
  ```
  stat (GNU coreutils) 8.32
  Copyright (C) 2020 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
  This is free software: you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.
  
  Written by Michael Meskes.
  ```

**Kubernetes Cluster:**  
- N/A

**Anything else we need to know?**  
It only happens when I install using `npm install`, it does not happen if I use the `curl` version to install it.

/kind bug

**Comment by LukasGentele** [comment]
@epierotto Thanks for the detailed bug report. Instead of checking the version, let's just not check anything and instead use `STAT=$(stat -L -f%z "$BINARY" 2>/dev/null || stat --printf="%s" "$BINARY" 2>/dev/null)` so that whatever is working first will determine the var value. I'll push that fix in a minute. I appreciate all the details you provided! Made it super easy to address this. Thanks!

**Comment by FabianKramm** [comment]
@epierotto this should work now with v5.10.0
