### ISSUE TITLE
Add DaemonSet to Component Chart

### ISSUE THREAD

**Issue by saruman9** [loft-sh/devspace#1366]
**Is your feature request related to a problem?**  
Without ability to use `DaemonSet` in the Component Chart we should use k8s manifests or other YAML-based solution.

**Which solution do you suggest?**  
Add [`DaemonSet`](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/) resource based on Deployments.

**Which alternative solutions exist?**  
Use k8s manifests or Helm chart.

/kind feature

**Comment by FabianKramm** [comment]
@saruman9 thanks for creating this issue! I'm not sure if we should add that since the component chart is mainly meant for rather simple deployments and not as a general abstraction chart for all kubernetes resources.

**Comment by saruman9** [comment]
Thank you for quick response.

After your words I thought, I think you are right. I will write a Helm chart for my complex deployment (I need to change image's name and tag for dev/production stages, it's only possible if used Helm chart or Kustomize). You can free to close the issue if you think it's not needed.
