### ISSUE TITLE
Add ".devspace/" entry into ".dockerignore" on "devspace init"

### ISSUE THREAD

**Issue by epierotto** [loft-sh/devspace#1371]
**What happened?**  
`devspace init` does not add `.devspace/` entry into `.dockerignore`

**What did you expect to happen instead?**  
I expect devspace to add `.devspace/` entry into `.dockerignore` since it's not required during image build.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Run `devspace init` in a folder with both `.gitignore` and `.dockerignore` files and check the entries added by devspace.

**Local Environment:**  
- DevSpace Version: 5.9.1
- Operating System: mac (Not sure is relevant)
- Deployment method: N/A

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@epierotto thanks for creating this issue! Yes we should add this

**Comment by FabianKramm** [comment]
@epierotto this was added with v5.11.0
