### ISSUE TITLE
Information about username/password for Chart is missed

### ISSUE THREAD

**Issue by saruman9** [loft-sh/devspace#1372]
**What happened?**  
Docs didn't have information about username/password for Chart, but [it's exist](https://github.com/loft-sh/devspace/blob/08c6ad9f2fb5f74aa1f7b9858a39e0f37da37135/pkg/devspace/config/versions/latest/schema.go#L570-L571).

I needed to fetch Chart from private registry and I used `upgradeArgs` (and other `*Args`) with `--username`/`--password` arguments for that, but I recently found, that the credentials configs exist.

**What did you expect to happen instead?**  
Docs should have this information, I think.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
See [the latest docs](https://github.com/loft-sh/devspace/blob/88fb767553d13047b235e2b595edce78092d170d/docs/pages/configuration/deployments/helm-charts.mdx#chart) for Chart.

**Local Environment:**  
- DevSpace Version: devspace version 5.10.0
- Operating System: linux
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: baremetal
- Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"archive", BuildDate:"2021-01-13T22:07:54Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

/kind bug

**Comment by FabianKramm** [comment]
@saruman9 thanks for creating this issue! Yes you are correct we should add this to our docs
