### ISSUE TITLE
--silent doesn't hide [info] log messages when "devspace run xxxx" is used

### ISSUE THREAD

**Issue by leventogut** [loft-sh/devspace#1373]
**What happened?**  

--silent doesn't hide [info] log messages when "devspace run xxxx" is used (devspace --silent enter works)
**What did you expect to happen instead?**  

be silent

**How can we reproduce the bug?** (as minimally and precisely as possible)  
➜  php-laravel-nginx-devspace git:(master) ✗ devspace --silent run artisan key:generate --show
[info]   Using namespace 'default'
[info]   Using kube context 'docker-desktop'
[info]   Opening shell to pod:container app-0:php
base64:xxxxxx
➜  php-laravel-nginx-devspace git:(master) ✗ devspace --silent enter -c php -- php artisan key:generate --show
base64:xxxxxxxx
➜  php-laravel-nginx-devspace git:(master) ✗ 

**Local Environment:**  
- DevSpace Version: devspace version 5.10.0
- Operating System: mac
- Deployment method: helm 

**Kubernetes Cluster:**  
- Cloud Provider: docker-desktop
- Kubernetes Version: [use `kubectl version`]
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@leventogut thanks for opening this issue! I suspect you call `devspace` within the command, correct? You will need to set the `--silent` in the command as well as devspace is not passing this flag to the underlying command. E.g.:
```yaml
commands:
- name: artisan
  command: "devspace --silent enter -c php -- php artisan key:generate --show"
```

**Comment by leventogut** [comment]
I am very sorry, not sure how I thought there was a problem. My mistake
