### ISSUE TITLE
Invalid namespace "successfully" created

### ISSUE THREAD

**Issue by saruman9** [loft-sh/devspace#1382]
**What happened?**  

A namespace with invalid format (for example, `test_test`) don't should be created, but DevSpace report that a namespace successfully created.

**What did you expect to happen instead?**  

DevSpace should check of creating of a namespace and report about an error.

**How can we reproduce the bug?**

```sh
devspace use namespace test_test
devspace deploy
```

DevSpace's output:
```
...
[done] √ Created namespace: test_test
[warn]   failed to create pull secret for registry: create pull secret: Unable to create image pull secret: namespaces "test_test" not found
...
```

**Local Environment:**  
- DevSpace Version: 5.10.0
- Operating System: linux
- Deployment method: helm | kubectl apply

**Kubernetes Cluster:**  
- Kubernetes Version: 
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"archive", BuildDate:"2021-03-25T19:02:48Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

/kind bug

**Comment by FabianKramm** [comment]
@saruman9 thanks for creating this issue! We'll change that in the next version
