### ISSUE TITLE
Using BuildKit builder engine + Kubernetes for remote building

### ISSUE THREAD

**Issue by saruman9** [loft-sh/devspace#1383]
**Is your feature request related to a problem?**  
Yes.

For building on a remote cluster I use Kaniko, but it has many issues (for example: [1](https://github.com/GoogleContainerTools/kaniko/issues/1468), [2](https://github.com/GoogleContainerTools/kaniko/issues/1600)) that make it take a long time to build.

**Which solution do you suggest?**  

Using [BuildKit](https://github.com/moby/buildkit) with building on a [Kubernetes cluster](https://github.com/moby/buildkit/tree/master/examples/kubernetes) with the possibility of [caching](https://github.com/moby/buildkit#registry-push-image-and-cache-separately).

**Which alternative solutions exist?**  

Using [Custom Build](https://devspace.sh/cli/docs/configuration/images/custom) with deployment of BuildKit's Pod/Deployment+Service.

/kind feature

**Comment by saruman9** [comment]
Similar solution used in the [Garden](https://garden.io/): [`cluster-buildkit`](https://docs.garden.io/guides/in-cluster-building#cluster-buildkit).

**Comment by FabianKramm** [comment]
@saruman9 thanks for creating this issue! Yes, we wanted to include buildkit building for the next version, since we also think this will be the future and has quite some promising advantages over kaniko and docker building in general.
