### ISSUE TITLE
Creating of a namespace is missed, when used `build` command and Kaniko builder

### ISSUE THREAD

**Issue by saruman9** [loft-sh/devspace#1384]
**What happened?**  

Namespace is not created when using Kaniko builder (as fallback) and DevSpace was started with the `build` command.

**What did you expect to happen instead?**  

Namespace should be created as for `dev` command.

**How can we reproduce the bug?**

```sh
devspace use namespace namespace-which-didnt-exist
devspace build # without local docker
```

DevSpace's output:
```
[fatal]  build images: create builder: Error creating kaniko builder: create pull secret: create pull secret: Unable to create image pull secret: namespaces "namespace-which-didnt-exist" not found
```

**Local Environment:**  
- DevSpace Version: 5.10.0
- Operating System: linux
- Deployment method: helm | kubectl apply

**Kubernetes Cluster:**  
- Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"archive", BuildDate:"2021-03-25T19:02:48Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

/kind bug

**Comment by FabianKramm** [comment]
@saruman9 thanks for creating this issue! Yes, currently devspace does not create a namespace in `devspace build`, but we can change this for the next release.
