### ISSUE TITLE
Add an option to show notes.txt when deploying a helm chart

### ISSUE THREAD

**Issue by kuuji** [loft-sh/devspace#1419]
**Is your feature request related to a problem?**  

Maybe? helm chart deployments currently do not show the rendered notes.txt after installation/upgrade.
Notes.txt can be a source of very useful debugging information for chart users.

**Which solution do you suggest?**  

I understand that showing notes.txt for all installed charts could get very verbose. So being able to enable it on a per deployment basis would be neat. Either via a field in the yaml or a flag on the cli.

**Which alternative solutions exist?**  

Currently none. Afaik the only way to get this information is to manually run `helm status`

**Additional context**  

I'd be down to help contribute on this if it's something you're interested in supporting. I'm assuming it would be something within this function -> https://github.com/loft-sh/devspace/blob/9f9e8cd495246746fc0af2b615d0fd8e2f1777e2/pkg/devspace/deploy/deployer/helm/deploy.go#L22-L107

potential something else to be able to query it in list deployments.

Edit: I guess also a new function here to get the status https://github.com/loft-sh/devspace/blob/9f9e8cd495246746fc0af2b615d0fd8e2f1777e2/pkg/devspace/helm/v3/client.go

/kind feature

**Comment by FabianKramm** [comment]
@kuuji thanks for creating this issue and offering your help! We can think about this, however I'm not sure if showing the complete `helm upgrade` output might not even be the better approach, as this could sometimes also help with debugging a chart as well.

**Comment by kuuji** [comment]
You make a good point @FabianKramm . I'll take a stab at it.

Since I'm here I might as well let you know that me and a few folks from my company started using devspace recently and absolutely love the tool. We're really impressed with it and have plans to push it across the entire org. We're using it for both dev and CI the deployment side is handled by gitops.

Thanks for making such a fantastic tool.
