### ISSUE TITLE
Push credentials don't work on cluster re-creation

### ISSUE THREAD

**Issue by joaomlneto** [loft-sh/devspace#1424]
**What happened?**

I'm currently trying to integrate my workflow into devspace, and am frequently creating/destroying clusters to experiment. I'm trying to put as much of the workload on the K8S cluster so that my warm laptop can survive the summer :-) OOT, but I have to say I love the potential devspace has. Thanks for the project!

If I re-create my Kubernetes cluster and container registry (via `terraform destroy && terraform apply`), I'm unable to build the image via kaniko, as it says it doesn't have permissions to push image:

```
[info]   Using namespace 'joaomlneto'
[info]   Using kube context 'admin@cluster'
[info]   Couldn't find a running docker daemon. Will fallback to kaniko
[info]   Building image 'rg.nl-ams.scw.cloud/my-namespace/myimage:XXXXXXX' with engine 'kaniko'
[warn]   Using CMD statement for injecting restart helper because ENTRYPOINT is missing in Dockerfile and `images.*.entrypoint` is also not configured
[done] √ Uploaded files to container
[done] √ Build pod has started
[info]   Printing logs of pod:container devspace-build-kaniko-pflrt:kaniko
E0424 21:53:27.458058       1 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "rg.nl-ams.scw.cloud/my-namespace/myapp:XXXXXXX": creating push check transport for rg.nl-ams.scw.cloud failed: GET https://api.scaleway.com/registry-internal/v1/regions/nl-ams/tokens?scope=repository%3Amy-namespace%2Fmyapp%3Apush%2Cpull&service=registry: unexpected status code 401 Unauthorized: {"message":"Unauthorized request"}
[fatal]  error building image rg.nl-ams.scw.cloud/my-namespace/myapp:XXXXXXX: error building image (Exit Code 1)
```

- Performing `docker login [host] -u [user] -p [password]` results in `Login Succeeded`.
- I've checked the token used by kaniko matches that of my docker client.

Refreshing my credentials makes it work again (until re-creation). I'm unsure if this is related to the cloud provider, or to devspace.

As an alternate workaround I've tried to delete the `.devspace` folder and re-run `devspace dev`, but it doesn't work.

**How can we reproduce the bug?**

1. Create cluster and container registry with Scaleway
2. Use kaniko to build image and check everything works properly
3. Destroy and re-create the cluster (and edit `~/.kube/config` with the new configuration)
4. Attempt to create the image using kaniko -- won't work due to insufficient push permissions.
5. Verify that credentials used by kaniko match those of the local docker client, and that `docker login` succeeds.
6. Create/refresh security and perform `docker login` with the new credentials.

**Local Environment:**  
- DevSpace Version: `devspace version 5.12.1`
- Operating System: mac
- Deployment method: helm (component chart)

**Kubernetes Cluster:**  
- Cloud Provider: Scaleway
- Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**

I'm unsure if this is caused by some stale devspace configuration lingering, or a problem with the cloud provider. I am more inclined towards the former, but as I'm unsure I'd ask you for assistance for debugging :-)

/kind bug

**Comment by FabianKramm** [comment]
@joaomlneto thanks for creating this issue! For me it look like the scaleway provider is the issue and that the token (that is used by devspace) is invalid after you recreate the cluster, until you relogin with your username and password which refreshes the token. 

Internally, DevSpace does not cache any registry credentials and will always just read the token from docker, but if docker returns a no longer valid token, there is not much we can do unfortunately.

**Comment by joaomlneto** [comment]
Indeed. Problem seems to be with docker caching the token from the previous registry which stops being valid on registry recreation.

Thanks for the clarification!
