### ISSUE TITLE
Setting SecurityContext of InitContainer in devspace.yaml

### ISSUE THREAD

**Issue by joaomlneto** [loft-sh/devspace#1425]
### Is your feature request related to a problem?

Yes! I'm running into problems due to `fs.inotify.max_user_watches` being set too low (`8192`) on the host node, and I'm unable to set the values.

A workaround is to set an initContainer on `devspace.yaml` that runs `sysctl -w vm.max_map_count=524288` with the container having `securityContext.privileged: true`.

However, I'm unable to set this security context. There doesn't seem to be a way in the documentation.

### Which solution do you suggest?

An *advanced* option to pass extra arguments to the init container.

/kind feature

**Comment by FabianKramm** [comment]
@joaomlneto Thanks for creating this issue! It's undocumented, but should work as it is a valid option in the [component-chart](https://github.com/loft-sh/component-chart/blob/master/templates/deployment.yaml#L341).
