### ISSUE TITLE
Allowing `kustomize edit` before applying

### ISSUE THREAD

**Issue by fg91** [loft-sh/devspace#1428]
**Is your feature request related to a problem?**  

My problem occurs when multiple users deploy the same deployment using `devspace dev --deployments=...` into the cluster as in this case there is a collision with the name of the resource, e.g. a pod. I'd like the name of e.g. a pod to be changed from e.g. `dummy-pod` to `dummy-pod-$USER` with the environment variable being evaluated before applying the manifest. Alternatively if the user name cannot be inserted it would also help to add a random string to the name of the pod in order to avoid the collision.

**Which solution do you suggest?**  

With kustomize I could for instance use a nameSuffix and do `kustomize edit set namesuffix $USER` before doing `kustomize build`. It would be great help if devspace could evaluate `kustomize edit` calls on the fly.

**Which alternative solutions exist?**  

I currently don't see any but am of course very interested in alternative solutions to my problem.

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
@fg91 thanks for creating this issue! Did you test out [hooks](https://devspace.sh/cli/docs/configuration/hooks/basics)? You could just run a `kustomize edit set namesuffix $USER` there.

**Comment by fg91** [comment]
> @fg91 thanks for creating this issue! Did you test out [hooks](https://devspace.sh/cli/docs/configuration/hooks/basics)? You could just run a `kustomize edit set namesuffix $USER` there.

Oh my, a whole new world opens 😄 
Thanks for the quick reply.
