### ISSUE TITLE
devspace open not working

### ISSUE THREAD

**Issue by ComaVN** [loft-sh/devspace#1432]
**What happened?**  

I try to open a port forwarding connection to a running pod, and `devspace open` exits without any error or logging after choosing `localhost` forwarding & a running pod.

**What did you expect to happen instead?**  
I expect `devspace open` to remain open and forward ports, or at the very least show an error why it can't do that

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Literally just run `devspace open`, choose `localhost`, and choose any pod with a service port to forward

**Local Environment:**  
- DevSpace Version: 5.12.1
- Operating System: Ubuntu Linux
- Deployment method: kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: DevSpace Cloud
- Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-16T18:16:59Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  
`devspace dev` works fine, and correctly opens the port forwarding

`kubectl port-forward` works fine as well.

`devspace open` used to work, but I'm not certain it broke at the same time that I last updated devspace.

I downgraded to v5.11.0, and then it works again. v5.12.0 it doesn't work either. After upgrading back to v5.12.1: same problem

I understand this could very well be hard to reproduce and depend massively on our k8s cluster config or something, but I'm at a loss on how to further diagnose this issue.

/kind bug

**Comment by FabianKramm** [comment]
@ComaVN thanks for creating this issue! Indeed, local portforwarding does not seem to work currently in `devspace open`. We issued a new release v5.12.2 that will fix this!

**Comment by ComaVN** [comment]
I upgraded to v5.12.2, and it works.

Thanks for the quick response!
