### ISSUE TITLE
File not synced by devspace

### ISSUE THREAD

**Issue by amishurov** [loft-sh/devspace#1442]
**What happened?**  
In our project we have multiple js files bundled by webpack. Also we have file with meta info about packed js budles. It is xml containing unique hashes i.e
```
<?xml version="1.0"?>
  <js-variables>
    <variable key="appEntryPoint" value="/webpackBuild/appEntryPoint.9a045712a3d479c28c5b.js"/>
  </js-variables>
 </xml>

```
When developer makes changes in source code this file also changed on the fly by gulp script. 
Finally, the problem is this file with meta info about bundles doesn't sync into pod. I think this behavior is effect of many files changing in short time, due webpack working

**What did you expect to happen instead?**  
This file with meta info should synced

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Haven't simple steps for reproduce :(

**Local Environment:**  
- DevSpace Version: 5.12.2
- Operating System: linux
- Deployment method: kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: bare metal cluster
- Kubernetes Version: 1.20.2

**Anything else we need to know?**  
Executed utility for track notify events on file that wasn't synced:
```
$ inotifywait -m ~/project/xhh/xml/js-variables.xml 
Setting up watches.
Watches established.

~/project/xhh/xml/js-variables.xml MODIFY 
~/project/xhh/xml/js-variables.xml OPEN 
~/project/xhh/xml/js-variables.xml MODIFY 
~/project/xhh/xml/js-variables.xml ATTRIB 
~/project/xhh/xml/js-variables.xml CLOSE_WRITE,CLOSE 
```
Logs in devspace container:
```[info]   Upstream - Handling 1472 removes
[info]   Upstream - Upload File 'xhh/xml/xsl-task.xml'
[info]   Upstream - Upload 1 create change(s) (Uncompressed ~0.00 KB)
[info]   Upstream - Successfully processed 1473 change(s)
[info]   Upstream - Handling 607 removes
[info]   Upstream - Upload 205 create change(s) (Uncompressed ~653.94 KB)
[info]   Upstream - Successfully processed 812 change(s)
[info]   Upstream - Upload 57 create change(s) (Uncompressed ~521.39 KB)
[info]   Upstream - Successfully processed 57 change(s)
[info]   Upstream - Upload File 'xhh/xsl_precompiled/content/feedback.xsl'
[info]   Upstream - Upload File 'xhh/xml/xsl-task.xml'
[info]   Upstream - Upload File 'xhh/xml/xsl-task.xml'
[info]   Upstream - Upload 3 create change(s) (Uncompressed ~5.14 KB)
[info]   Upstream - Successfully processed 3 change(s)
[info]   Upstream - Upload 7493 create change(s) (Uncompressed ~49441.08 KB)
[info]   Upstream - Successfully processed 7493 change(s)
[info]   Upstream - Upload 1211 create change(s) (Uncompressed ~148090.08 KB)
[info]   Upstream - Successfully processed 1211 change(s)
```
Only suggest but in issue https://github.com/loft-sh/devspace/issues/1296 random files were not synced. In current case only this file is not synced.
When I change file directly in editor sync works as expected.

/kind bug

**Comment by amishurov** [comment]
Also may be this info will be useful:
```
$ stat ~/project/xhh/xml/js-variables.xml
  File: ~/project/xhh/xml/js-variables.xml
  Size: 1701      	Blocks: 8          IO Block: 4096   regular file
Device: 801h/2049d	Inode: 19959059    Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 2000/      hh)   Gid: ( 2000/      hh)
Access: 2021-05-12 12:09:37.098000000 +0300
**Modify: 2021-04-22 16:53:10.604000000 +0300**
Change: 2021-05-12 13:57:48.018553082 +0300
 Birth: -
```
File was trunctated and written, but modify time wasn't changed.

**Comment by FabianKramm** [comment]
@amishurov thanks for reporting this issue! Did the size of the file change? Currently devspace uses those 2 metrics to find out if a file has changed (for speed reasons), however we could also think about calculating hashes if DevSpace notices a change but the mtime and size is the same as before.

**Comment by amishurov** [comment]
@FabianKramm size and modify time wasn't changed due gulp script rewrites bundle hashes in this file
```
$ ls -lat xhh/xml/js-variables.xml && md5sum xhh/xml/js-variables.xml
-rw-rw-r-- 1 hh hh 1701 Apr 22 16:53 xhh/xml/js-variables.xml
3c4b72bc26b2962d3203471aed904940  xhh/xml/js-variables.xml
# gulp changed content here
$ ls -lat xhh/xml/js-variables.xml && md5sum xhh/xml/js-variables.xml
-rw-rw-r-- 1 hh hh 1701 Apr 22 16:53 xhh/xml/js-variables.xml
59381db9ba0662a0571a52642713cda8  xhh/xml/js-variables.xml
```

**Comment by amishurov** [comment]
also find issue why mtime isn`t changed 
https://github.com/gulpjs/gulp/issues/2193

**Comment by FabianKramm** [comment]
Okay I see, the problem then really is that the change does not change size or mtime of the file which causes DevSpace to miss this change. As a workaround for now you could try to update the mtime of the file after the gulp change which will signal DevSpace to sync the file.

**Comment by amishurov** [comment]
Looks like all works fine now, thanks for support!
