### ISSUE TITLE
Add hooks[*].wait.ready

### ISSUE THREAD

**Issue by fmc100** [loft-sh/devspace#1489]
**Is your feature request related to a problem?**  
Yes, I want to use devspace hooks to wait for my db to be ready and not just running.

**Which solution do you suggest?**  
Something like [this](https://github.com/loft-sh/devspace/blob/affdf137c5695833a7135bd58313aa8a28d92d00/pkg/devspace/hook/wait.go#L119) but for ready since it is grabbing info from almost the same place.

**Which alternative solutions exist?**  
Creating an init container and waiting for the db to be up before starting my service.
Alternatively making devspace wait all db deployments.

**Additional context**  
Would be really cool to be able to wait for my db to be running and ready before allowing my service to be up.

/kind feature

**Comment by FabianKramm** [comment]
@fmc100 thanks for creating this issue! Yes that makes sense, currently we only check if the container is running, but not ready, however we can add this to the condition.

**Comment by fmc100** [comment]
thanks
