### ISSUE TITLE
OCI error on WSL2

### ISSUE THREAD

**Issue by DanArlowski** [loft-sh/devspace#1561]
**What happened?**  

when running `devspace dev` with custom chart, the chart is getting installed,
everything is running, syncing is starting (and as interpented from the logs - finishing )
and the we get the error
```
[1;32m[done] √ [0mPort forwarding started on 2000:8080 (devspace/dev-ui-chartname-66dc578786-qm4vx)
[1;36m[wait] [0m| Starting the ui server... (0s)
                                             
#########################################################
[1;36m[info]   [0mDevSpace UI available at: [1;37mhttp://localhost:8090[0m
#########################################################

[34m[0:sync] [0mWaiting for pods...
[34m[0:sync] [0mStarting sync...
[34m[0:sync] [0mSync started on /mnt/c/Users/chartname/repos/repo <-> . (Pod: devspace/devspace-chartname-7997f8c94d-sskml-devspace)
[34m[0:sync] [0mWaiting for initial sync to complete
[1;36m[info]   [0mOpening 'http://localhost:2000' as soon as application will be started (timeout: 4m0s)
[1;36m[info]   [0mOpening 'http://localhost:8090' as soon as application will be started (timeout: 4m0s)
[1;36m[info]   [0mOpening shell to pod:container [1;37mdevspace-chartname-7997f8c94d-sskml-devspace[0m:[1;37mdevspace[0m
OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: no such file or directory: unknown
```

**What did you expect to happen instead?**  

devspace_start.sh should kick up and start running

it does work on Mac and ubuntu 18.04,
just not WSL

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. WSL instance in a windows 10
2. kubectl version 21
3. EKS cluster with admin permissions

as you can see from the logs its pretty tough to understand exactly what caused the OCI crash.

The fact that it works on Mac/Linux 18.04 (VM from vagrant) 
proves its not a configuration issue.

**Local Environment:**  
- DevSpace Version:  latest (5.14.4)
- Operating System:  WSL2 on linux
- Deployment method: helm custom chart

**Kubernetes Cluster:**  
- Cloud Provider: eks
- Kubernetes Version: 
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:56:19Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@DanArlowski thanks for creating this issue! Could you share your `devspace.yaml`, seems like this might be a problem with the container or entrypoint

**Comment by DanArlowski** [comment]
As it seems, the problem was that we run it in an environment that was not aware of how to run the 
`devspace_start.sh` Script (the shebang was for bash)

workaround - we altered the command to be passed to the container to be:
`command:
- bash
- devspace_start.sh`

And it got it to work correctly
