### ISSUE TITLE
devspace deploy -d does not always force redeploy

### ISSUE THREAD

**Issue by hariprasadiit** [loft-sh/devspace#1571]
**What happened?**  
`--force-deploy` only force re-deploys if images are built

**What did you expect to happen instead?**  
`--force-deploy` should re-deploy all the deployments with or without building image

**How can we reproduce the bug?** (as minimally and precisely as possible)  
run `devspace deploy -d` when there's an existing deployment

**Local Environment:**  
- DevSpace Version: 5.14.4
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: other
- Kubernetes Version: 1.21.1

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@hariprasadiit thanks for creating this issue! Could you provide a minimal example of when this happens?

**Comment by hariprasadiit** [comment]
Thanks for reply. 

I've tried [quickstart example](https://github.com/loft-sh/devspace/tree/master/examples/quickstart). `-d` options doesn't force redeploy.

For my clarity, `-d` should purge and deploy right? or will it only be effective if deployment config has changed?

**Comment by FabianKramm** [comment]
@hariprasadiit Ah I see, `-d` does not purge and redeploy, it only forces helm to rerun again and if there are no changes nothing will happen. If you want to purge and redeploy you have to run `devspace purge && devspace dev`

**Comment by hariprasadiit** [comment]
Understood. Thanks for the clarification.

Thank you for the great project
