### ISSUE TITLE
devspace-restart-helper replaces devspacehelper in upstream sync command

### ISSUE THREAD

**Issue by abhijithkumar123** [loft-sh/devspace#1572]
**What happened?**  
I see the following error when sync is run

> Error: Sync Error on <localSubPath>: Sync - connection lost to pod aagina/app-aagina-f4d97fb7d-5x9wz: Error: unknown flag: --override-permissions
Usage:
  devspace-restart-helper sync upstream [flags]
Flags:
      --batchargs strings        Args that should be used for the command that is run after a batch of changes is processed
      --batchcmd string          Command that should be run after a batch of changes is processed
      --dircreateargs strings    Args that should be used for the command that is run during a directory create
      --dircreatecmd string      Command that should be run during a directory create
      --exclude strings          The exclude paths for upstream watching
      --filechangeargs strings   Args that should be used for the command that is run during a file create or update
      --filechangecmd string     Command that should be run during a file create or update
  -h, --help                     help for upstream
unknown flag: --override-permissions command terminated with exit code 1
[1:sync] Sync stopped

**What did you expect to happen instead?**  
Upstream sync to run with /tmp/devspacehelper but not with devspace-restart-helper

**How can we reproduce the bug?** (as minimally and precisely as possible)  
To give a little more context, our project is written in go. In order to sync the binary, the following config is added to devspace.yaml:

> - labelSelector:
      app: AppName
    containerName: "container-name"         # string   | Container name to use after selecting a pod
    containerPath: /app
    localSubPath: ./app             # string   | Path in the container that should be synchronized with localSubPath (Default is working directory of container ("."))
    excludePaths:
    - 'Makefile'
    - 'main.go'
    - 'README.md'
    - 'docs'
    - 'main_test.go'
    - '.*'
    disableDownload: true
    namespace: ${DEVSPACE_NAMESPACE}               # string   | Kubernetes namespace to select pods in
    onUpload:                       # struct   | After a file/folder has been uploaded to the container...
      restartContainer: true

Since I'm not building the image locally but sync'ing my changes to an already deployed container, I manually modified entrypoint of this project in Dockerfile as follows:

> ENTRYPOINT ["/.devspace/devspace-restart-helper", "/app/AppName"]

This whole setup works flawlessly on a mac but on centos (8 in particular), the devspacehelper upstream sync command is somehow replaced with devspace-restart-helper upstream sync.

In order to reproduce, remove the go binary from local (if previously built), this will remove the binary in the container as well. Now, do build static go binary with the following command:

> go build -o api -ldflags='-extldflags=-static' -tags sqlite_omit_load_extension,osusergo,netgo .

This will now run that upstream sync command but with devspace-restart-helper instead of devspacehelper

**Local Environment:**  
- DevSpace Version: 5.14.4
- Operating System: CentOS 8
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: azure
- Kubernetes Version: 1.20.2

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@abhijithkumar123 thanks for creating this issue! It seems to me as that there are 2 problems here:
1. I believe the correct binary is actually called (not the /.devspace/devspace-restart-helper), however the usage message is wrong and the devspacehelper actually had `devspace-restart-helper` previously in the helper text and we did not change that. You can see that by calling it in a container via `kubectl exec ... -- /tmp/devspacehelper sync upstream -h`. We'll fix the message for the next release, but this should have no negative impact on your problem.
2. The actual problem seems to be caused by an somehow older devspacehelper binary that was uploaded to your container, hence why the flag `override-access` was not found. Could you execute `kubectl exec ... -- /tmp/devspacehelper version` in the target container and provide us with the output to see what version was uploaded to the container?

**Comment by abhijithkumar123** [comment]
I will run the command and give you the output. Can you point me to the latest devspace restart helper code in your repo?

**Comment by FabianKramm** [comment]
@abhijithkumar123 you can find the latest devspace restart helper code at https://github.com/loft-sh/devspace/tree/master/helper

**Comment by abhijithkumar123** [comment]
> @abhijithkumar123 thanks for creating this issue! It seems to me as that there are 2 problems here:
> 1. I believe the correct binary is actually called (not the /.devspace/devspace-restart-helper), however the usage message is wrong and the devspacehelper actually had `devspace-restart-helper` previously in the helper text and we did not change that. You can see that by calling it in a container via `kubectl exec ... -- /tmp/devspacehelper sync upstream -h`. We'll fix the message for the next release, but this should have no negative impact on your problem.
> 2. The actual problem seems to be caused by an somehow older devspacehelper binary that was uploaded to your container, hence why the flag `override-access` was not found. Could you execute `kubectl exec ... -- /tmp/devspacehelper version` in the target container and provide us with the output to see what version was uploaded to the container?

The version output of that command is 5.14.4 same as the devspace we installed using yum.

**Comment by FabianKramm** [comment]
@abhijithkumar123 thanks for the info, what is the output if you run:
```
kubectl exec ... -- /tmp/devspacehelper sync upstream -h
```
