### ISSUE TITLE
Bug: pod name from devspace dev log is in red color and it looks like an error

### ISSUE THREAD

**Issue by ansonlc** [loft-sh/devspace#1583]
**What happened?**  
pod name from devspace dev log is in red color and it looks like an error

**What did you expect to happen instead?**  
I would expect to see a different color instead of red color

**How can we reproduce the bug?** (as minimally and precisely as possible)  
![Screen Shot 2021-08-23 at 4 24 36 PM](https://user-images.githubusercontent.com/6512251/130540344-9b7820c2-d925-4604-bf39-61adb6ce90d2.png)

**Local Environment:**  
- DevSpace Version: 5.14.4
- Operating System: mac
- Deployment method: helm apply

**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: 1.17.17

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@ansonlc thanks for creating this issue! We can remove red from the color palette to make this a little bit more clear

**Comment by ansonlc** [comment]
@FabianKramm cool, thanks a lot!

**Comment by FabianKramm** [comment]
works with v5.16.0
