### ISSUE TITLE
Log Streaming - bufio.Scanner: token too long

### ISSUE THREAD

**Issue by BirknerAlex** [loft-sh/devspace#1596]
**What happened?**  

When running `devspace dev` it starts to stream all log files from all containers, after some minutes devspace stops from streaming the log files with the following error:

```
[api-statefulset] Warning: Error streaming logs for dev-alex/panel-statefulset-0/panel: bufio.Scanner: token too long
[panel-statefulset] Start streaming logs for dev-alex/panel-statefulset-0/panel
```

But the strange thing is in the above example the container `api-statefulset` stopped streaming the logs, the container `panel-statefulset` still streams the output. But the error `dev-alex/panel-statefulset-0/panel: bufio.Scanner` indicates a issue with the still working container. 

My idea would be the log stream isn't thread safe, one container message kills the streaming of another container - but just an idea. Otherwise I don't understand why the line from the `api-statefulset` shows an error from the container `panel-statefulset`.

**What did you expect to happen instead?**  

Streaming all container logs without aborting.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Multiple containers streaming a lot of data?

**Local Environment:**  
- DevSpace Version: 5.14.4
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: DigitalOcean
- Kubernetes Version: 
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
should be fixed with the newer DevSpace versions
