### ISSUE TITLE
Run some predefined script upon ctrl+c i.e. interrupt

### ISSUE THREAD

**Issue by kickthemooon** [loft-sh/devspace#1641]
After I finished my devspace work session I stop the command that was running / syncing.
After that I might want to do some things like cleanup or similar.

What might be nice is if I could specify a script that should be run upon ctrl+c i.e. interrupt in the devspace.yaml.
Same thing, specifying a script that should be run upon initial sync.

/kind feature

**Comment by FabianKramm** [comment]
@kickthemooon thanks for creating this issue! We could think about adding a hook for this, with the newest version we already have an hook for before and after initial sync (see https://devspace.sh/cli/docs/configuration/hooks/basics)

**Comment by FabianKramm** [comment]
Works with event `devCommand:interrupt` now
