### ISSUE TITLE
Generate the json schema for config file

### ISSUE THREAD

**Issue by antonlisovenko** [loft-sh/devspace#1652]
Hi guys.

Would be great if devspace provided the json schema generated by the Go struct for the config. Quick googled this [https://github.com/alecthomas/jsonschema](https://github.com/alecthomas/jsonschema)

Having json schema allows to import it to an IDE and get an auto-completion/validation support while editting config.

thanks for the great product!

**Comment by FabianKramm** [comment]
@antonlisovenko thanks for creating this issue! Yes, I think we could add a json schema

**Comment by leventogut** [comment]
Duplicate of #1146
