### ISSUE TITLE
Wrong remote folder with windows host

### ISSUE THREAD

**Issue by jpambrun** [loft-sh/devspace#1677]
**What happened?**  
On windows under msys2 I am running :
``` shell 
devspace sync -n namespace --upload-only --pod=podname --local-path=/c/Users/user/work/ --container-path=/app
```

In the container I can't find `/app/`, however I can find a `C:/Users/Users/scoop/apps/msys2/2021-07-25/app/` containing my files (which is odd to see in Linux..)

**What did you expect to happen instead?**  

I expect to see my files under the remote path of  `/app/`

**How can we reproduce the bug?** (as minimally and precisely as possible)  

see "What happened?"

**Local Environment:**  
- DevSpace Version: [use `devspace --version`]
devspace version 5.15.0
- Operating System: **windows** | linux | mac
- Deployment method: helm | **kubectl apply**

**Kubernetes Cluster:**  
- Cloud Provider: **rancher-desktop**
- Kubernetes Version: [use `kubectl version`]
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4+k3s1", GitCommit:"3e250fdbab72d88f7e6aae57446023a0567ffc97", GitTreeState:"clean", BuildDate:"2021-08-19T19:09:53Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  
I found that using `--container-path=app` instead of `--container-path=/app` (as per documentation) works okay.

/kind bug

**Comment by FabianKramm** [comment]
@jpambrun thanks for reporting this issue! Does the same problem occur if you use
```
devspace sync -n namespace --upload-only --pod=podname --local-path=C:\Users\user\work--container-path=/app
```
?

**Comment by jpambrun** [comment]
Sorry for the late response. 

I found the reason for this issue. It has nothing to do with devspace. I am using the windows devspace.exe and when invoking windows executable from msys bash it will convert `/` to the root for msys' installation. So `notepad.exe /etc/hosts` will become `notepad.exe C:/Users/<user>/scoop/apps/msys2/2021-07-25/etc/hosts` and "just work". However `devspace --container-path=/app` becomes `devspace --container-path=C:/Users/<user>/scoop/apps/msys2/2021-07-25/etc/hosts` which makes no sense .. This was very unexpected to me and I still don't know how to work around it.. Apology for the false positive.

**Comment by jpambrun** [comment]
Five more minutes of googling and the right keywords is all I needed to find the solution. 

Setting `MSYS_NO_PATHCONV=1` or prepending an extra slash (e.g. `--container-path=//app`) should solve it, but I didn't get a chance to test yet.
