### ISSUE TITLE
`onError.images.all` hook not being triggered

### ISSUE THREAD

**Issue by antonlisovenko** [loft-sh/devspace#1681]
**What happened?**  

Have specified the following hook to catch authentication errors:

```
  - command: |
      echo "ERROR: $DEVSPACE_HOOK_ERROR"
    when:
      onError:
        images: all
```

The build is failing as I'm not authenticated to Docker registry but the hook doesn't run:

```
[info]   Using namespace 'anton-lisovenko-ns'
[info]   Using kube context 'arn:aws:eks:us-west-2:814074717971:cluster/sendoso-dev-cluster'
[info]   Building image '<account>.dkr.ecr.us-west-2.amazonaws.com/<image>:PoOqdxf' with engine 'docker'
[fatal]  error building image <account>.dkr.ecr.us-west-2.amazonaws.com/<image>:PoOqdxf: Error during image registry authentication: Error response from daemon: login attempt to https://<account>.dkr.ecr.us-west-2.amazonaws.com/v2/ failed with status: 403 Forbidden
```

**What did you expect to happen instead?**  

I expected the hook to be run after an error so I could show the correct `docker login` command that an engineer must run to fix the error

**Local Environment:**  
5.16.0
MacOS

/kind bug

**Comment by FabianKramm** [comment]
@antonlisovenko thanks for creating this issue! Yes you are correct it seems the `v1beta10` does not work correctly there, but the new `v1beta11` works:
```yaml
version: v1beta11
hooks:
  - command: |
      echo "ERROR: $DEVSPACE_HOOK_ERROR"
    events: ["error:build:*"]
```

**Comment by antonlisovenko** [comment]
Hi @FabianKramm thanks, yes, this event works perfectly!
