### ISSUE TITLE
createPullSecret default (false) has no effect

### ISSUE THREAD

**Issue by ragnarpa** [loft-sh/devspace#1718]
**What happened?** 

The behaviour for default value (false) of createPullSecret described at https://devspace.sh/cli/docs/configuration/images/pull-secrets does not match reality. Docker account credentials are still uploaded as Kubernetes Secrets.

**What did you expect to happen instead?**  

No Docker account credentials stored as Secrets in Kubernetes cluster.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Define an image in devspace.yaml without createPullSecret setting and start the `dev` command.

**Local Environment:**  
- DevSpace Version: 5.14.4
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: other
- Kubernetes Version: v1.20.9

**Anything else we need to know?**  

/kind bug

**Comment by pratikjagrut** [comment]
Hi, @ragnarpa,  thank you for creating this issue. 

Here the default value of `createPullSecret` is `true` not `false`.  So only value we can pass is `createPullSecret: false` to deactivate it. We'll redress the docs.
