### ISSUE TITLE
The default value of dev.ports.forward[*].bindAddress is "localhost", as opposed to "0.0.0.0"

### ISSUE THREAD

**Issue by markszente** [loft-sh/devspace#1720]
The [docs](https://devspace.sh/cli/docs/configuration/development/port-forwarding#bindaddress) seem to suggest the default value of `bindAddress` is "0.0.0.0", while in reality [it is](https://github.com/loft-sh/devspace/blob/master/pkg/devspace/services/port_forwarding.go#L156) "localhost". 

Having it as localhosts makes absolute sense, but the docs should be updated to reflect the actual state of the code. 

/kind bug

**Comment by pratikjagrut** [comment]
Closed this issue with regards to PR #1722.
