### ISSUE TITLE
File sync not working on macOS case insensitive file system

### ISSUE THREAD

**Issue by ragnarpa** [loft-sh/devspace#1743]
**What happened?**  

File sync not working on macOS case insensitive file system.

**What did you expect to happen instead?**  

File sync working on macOS regardless of case sensitivity.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

https://github.com/ragnarpa/DevspacePathLetterCaseBug

**Local Environment:**  
- DevSpace Version: 5.16.2
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: other
- Kubernetes Version: v1.21.5

**Anything else we need to know?**  

/kind bug

**Comment by pratikjagrut** [comment]
fix is merged.
