### ISSUE TITLE
devspace deploy --profile does not allow multiple values

### ISSUE THREAD

**Issue by apneagu** [loft-sh/devspace#1760]
**What happened?**  
running `devspace deploy --profile p1 p2` throws an error `[fatal]  Couldn't find profile 'p1 p2'` instead of using p1 as parent of p2 (like devspace dev does)

**What did you expect to happen instead?**  
behave as `devspace dev`

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Define 2 profiles and try to use one as parent of the other

**Local Environment:**  
- DevSpace Version: [use `devspace --version`]
- devspace version 5.17.0
- Operating System: windows | linux | mac
- window 10

/kind bug

**Comment by FabianKramm** [comment]
@apneagu thanks for creating this issue! You can use `devspace deploy --profile p1 --profile p2` which should work as expected.

**Comment by apneagu** [comment]
thanks ! my problem was actually an yaml configuration. we had a thread on slack about this. thanks again for your help !
