### ISSUE TITLE
Render command requires the presence of a kube config file but does not use it

### ISSUE THREAD

**Issue by wollowizard** [loft-sh/devspace#1768]
**What happened?**  
The "devspace render" command requires a kube config file but does not really use it.
when running `devspace render --skip-push` in an environment with no kube config file, I get
```
[fatal]  Unable to create new kubectl client: kube config is invalid: please make sure you have an existing valid kube config. You might want to check one of the following things:
Make sure you can use 'kubectl get namespaces' locally

```
**What did you expect to happen instead?**  

It would be nicer if the render command did not actually require a kube config file. This would make it simpler in a CI/CD environment, where we don't have the kube config setup.

I'd expect the render command to just print the manifests. so they could be used to be pushed to an IaC repo, in a gitops approach.
Render does probably not really need a k8s connection anyway ( I tried with adding a formally valid but not real kube config file and it seems to work.

**How can we reproduce the bug?**
```
FROM alpine:latest
RUN apk --no-cache add curl
RUN curl -s -L "https://github.com/loft-sh/devspace/releases/latest" | sed -nE 's!.*"([^"]*devspace-linux-amd64)".*!https://github.com\1!p' | xargs -n 1 curl -L -o devspace && chmod +x devspace && install devspace /usr/local/bin;
COPY devspace.yaml .
CMD devspace render --skip-push && echo "All done"
```

**Local Environment:**  
Using helm for deployment, as part of a gitlab pipeline

/kind bug

**Comment by FabianKramm** [comment]
@wollowizard thanks for creating this PR! We'll need to investigate if `helm template` is able to run correctly without a kube context present. In general, we could also think about printing this as a warning instead of fatal and continue with a mock kube config that works until a real Kubernetes request has to be made.

**Comment by wollowizard** [comment]
hi @FabianKramm, thanks for checking. For now, I've found a workaround by creating a fake but formally valid kube config file. But it would be much better if we could have all commands fail as late as possible

**Comment by pratikjagrut** [comment]
Fix for this issue is merged closing this issue. Thanks.
