### ISSUE TITLE
devspace build tries to create a namespace? Shouldn't it also work without a kubernetes cluster?

### ISSUE THREAD

**Issue by wollowizard** [loft-sh/devspace#1769]
**What happened?**  
I'm running `devspace build`as one of the steps of a CI/CD pipeline, where I only want to build and push the images.
I don't have a valid kube config file because I don't intend to deploy the images at this stage.
Without a valid kube config file, I get:
```
Unable to create new kubectl client: kube config is invalid: please make sure you have an existing valid kube config. You might want to check one of the following things:
* Make sure you can use 'kubectl get namespaces' locally
```

If I create a formally valid but fake kube config file, I get:
```
[fatal]  unable to create namespace: get namespace: Get "https://kubernetes.docker.internal:6443/api/v1/namespaces/feat1": dial tcp: lookup kubernetes.docker.internal on 169.254.169.254:53: no such host
```

**What did you expect to happen instead?**  
It should just build and push the images.. Why does it try to create a namespace?

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Just put a formally valid but not real kube config file in ~/.kube/config

**Local Environment:**  
devspace version 5.17.0.
mac and linux.

**Kubernetes Cluster:**  
None

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@wollowizard thanks for creating this issue! DevSpace tries to verify if the current namespace exists and if not tries to create it, in this case it cannot retrieve the current namespace because of the no such host error. It seems to me that the kubernetes cluster is not reachable with the kubeconfig you have provided

**Comment by pratikjagrut** [comment]
Hi @wollowizard good point. Thanks.
Kaniko and buildkit need valid kubeconfig to do incluster image build but we can try to refactor the build to not use the kubeconfig if it's not doing incluster build.

**Comment by wollowizard** [comment]
> Hi @wollowizard good point. Thanks. Kaniko and buildkit need valid kubeconfig to do incluster image build but we can try to refactor the build to work without kubeconfig if it's not doing incluster build.

Hello Pratik, that would be realy useful. we are indeed using docker desktop (local) and Docker-in-Docker service (gitlab pipeline), not kaniko or buildkit. It would be great if you could do a "lazy initialization" of the k8s cluster connection, in order to initialize it just if it is really needed.

**Comment by wollowizard** [comment]
> @wollowizard thanks for creating this issue! DevSpace tries to verify if the current namespace exists and if not tries to create it, in this case it cannot retrieve the current namespace because of the no such host error. It seems to me that the kubernetes cluster is not reachable with the kubeconfig you have provided

Hello @FabianKramm , I think you're absolutely correct. The point is, I do not really want or need to create a namespace on any cluster. I'm using this in a a build step of a pipeline with multiple steps. I'm using docker in docker for the build (no kakino). So I don't really want to configure devspace to access any cluster and try to create any namespace, just to build and push the image to the docker registry.


Indeed even at a later stage (deplyoment step of the pipeline) I don't want devspace to connect to k8s, but I'll just "render" the manifests ( [see separate issue](https://github.com/loft-sh/devspace/issues/1768) )and push them to my gitops repo, where that config will be picked up and deployed in k8s automatically (think argocd).


I believe devspace can be a great tool on local running minikube / k8s in docker desktop, but also on remote pipelines with a gitops approach. In order to do the latter, I'd ask you to please lazily initialize the k8s connection only when and if really necessary. Or maybe provide a flag to skip the k8s cluster steps (like a dry run ..)

**Comment by wollowizard** [comment]
@FabianKramm @pratikjagrut Created a PR. Thanks for taking a look
