### ISSUE TITLE
Increase the --max flag value for helm list 

### ISSUE THREAD

**Issue by nachin** [loft-sh/devspace#1772]
**Is your feature request related to a problem?**  
We use devspace during our CI/CD pipeline to create preview environments. We usually have a large number of preview environments in the same namespace. On occasion the results for `devspace list deployments` will show that all deployments are not deployed even though the deployments have been provisioned without issue. I suspect the cause of this is that we have over 256 helm releases in this namespace regularly so the releases that devspace is attempting to validate will not show up on that list and results in a status of "not deployed".

**Which solution do you suggest?**  
Either adding the --max flag with a larger value when listing helm releases  or allow this to be selected by the user. I believe that if --max is set to 0 it will return whatever the servers default value is. 

**Which alternative solutions exist?**  
I don't know of any

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
@nachin thanks for reporting this! Yes we can increase the limit that shouldn't be a problem

**Comment by pratikjagrut** [comment]
Hi, @nachin we have set `--max=0` and released it in v5.18.0. Will you let us know if it's working fine for your use case and if it's ok to close this issue?

**Comment by nachin** [comment]
just tested this and the change has resolved the issue. Thank you
