### ISSUE TITLE
Undefined resources for persistPaths option.

### ISSUE THREAD

**Issue by emoreth** [loft-sh/devspace#1775]
**Is your feature request related to a problem?**
Some people either want to, or setup their clusters to require `resources.limits` and `resources.requests` in order to provision machines to the cluster.

The issue relies on `persistPaths` creating an `initContainer` without resources.

**Which solution do you suggest?**

Add an option to define `resources` value for `persistPaths` in devspace.yaml.

It would also be nice to mention that it works using initContainers in the docs as it took me a couple hours to figure that out.

**Which alternative solutions exist?**

N/A

**Additional context**

/kind feature

**Comment by LukasGentele** [comment]
We may want to think about adding resource limits and requests by default, plus add a general option to modify the container spec or merge values into the spec. Otherwise, we'll have another issue in 2 weeks asking for yet another thing to add for initContainers.
