### ISSUE TITLE
skip deploy and build in devspace init

### ISSUE THREAD

**Issue by EdwinPhilip** [loft-sh/devspace#1779]
**Is your feature request related to a problem?**  
No

**Which solution do you suggest?**  
Most of the projects that i have already has a CI CD pipeline job in Jenkins. We mainly use devspace to replace pods and and start sync, with opening a terminal in the replace pod, so that developers  can start the server in development mode manually by running some commands. 
When i start `devpsace init` to integrate existing projects, i would like to skip deployment and skip build image from my local.
Basically i would like the generated `devspace.yaml` to not have `deployments` , `pullSecrets`, `profiles` and `hooks` that pull external charts etc.
`devspace init` ask questions necessary only for `dev.sync`, `dev.ports`, `dev.replacePods`, `dev.terminal`, `dev.open` (only `dev` section in the yaml is preferred)

NOTE: We are using only `devspace dev` for application development
**Which alternative solutions exist?**  
`devspace init` can have `--skip-deploy` `--skip-build` options

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
@EdwinPhilip thanks for creating this issue! If you're only using the `dev` section, why not copy a template `devspace.yaml` and adjust it to your needs? I guess `devspace init` is mostly tailored to show off most of devspace's features, so stripping out all the parts through flags would make the process a lot more complicated and probably still not as flexible as you would like.

**Comment by EdwinPhilip** [comment]
Makes sense if its complicated. closing the issue.
