### ISSUE TITLE
Render command doesn't render manifest userspace information

### ISSUE THREAD

**Issue by enricopesce** [loft-sh/devspace#1782]
**What happened?**
If I render the manifest with the current commands

devspace use namespace test
devspace render --silent

the manifest misses any content about the namespace definition

**What did you expect to happen instead?**
I expect the namespace definition in the render command

/kind bug

**Comment by LukasGentele** [comment]
Are you using the component chart? If yes, please see this issue: https://github.com/loft-sh/component-chart/issues/60

**Comment by enricopesce** [comment]
no I'm using kustomize!

Il Ven 26 Nov 2021, 17:57 Lukas Gentele ***@***.***> ha
scritto:

**Comment by LukasGentele** [comment]
Thanks for clarifying. Why don't you add the namespace definition to your kustomization then? We are effectively just calling kustomize for the actual rendering AFAIK and showing the namespace seems not their default behavior (and not in Helm either).
