### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bforchhammer** [loft-sh/devspace#1818]
**What happened?**  

After upgrading devspace to version 5.18.0 many commands, e.g. `devspace dev` or `devspace deploy`, error with the following message:

```
❯ devspace dev
[info]   Using namespace 'test'
[info]   Using kube context 'docker-desktop'
[warn]   Cyclic dependency found:
...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x5402860]

goroutine 1 [running]:
github.com/loft-sh/devspace/pkg/devspace/dependency.(*Dependency).Name(0x56bf680)
        /Users/runner/work/devspace/devspace/pkg/devspace/dependency/dependency.go:425
github.com/loft-sh/devspace/pkg/devspace/dependency.(*manager).executeDependenciesRecursive(0xc000124440, {0xc000dbb110, 0xc000677400}, {0xc000677400, 0x5, 0x4400ce5}, {0x0, 0x0, 0x0}, {0x0, ...}, ...)
        /Users/runner/work/devspace/devspace/pkg/devspace/dependency/dependency.go:271 +0x1b0
github.com/loft-sh/devspace/pkg/devspace/dependency.(*manager).executeDependenciesRecursive(0xc000124440, {0xc0003a5b58, 0xc000677480}, {0xc000677480, 0x6, 0x0}, {0x0, 0x0, 0x0}, {0x0, ...}, ...)
        /Users/runner/work/devspace/devspace/pkg/devspace/dependency/dependency.go:283 +0x451
github.com/loft-sh/devspace/pkg/devspace/dependency.(*manager).executeDependenciesRecursive(0xc000124440, {0x0, 0x0}, {0xc0011a2600, 0xb, 0x52}, {0x0, 0x0, 0x0}, {0x0, ...}, ...)
        /Users/runner/work/devspace/devspace/pkg/devspace/dependency/dependency.go:283 +0x451
github.com/loft-sh/devspace/pkg/devspace/dependency.(*manager).handleDependencies(0xc000124440, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x30, 0x1a, 0x1, ...)
        /Users/runner/work/devspace/devspace/pkg/devspace/dependency/dependency.go:235 +0x471
github.com/loft-sh/devspace/pkg/devspace/dependency.(*manager).ResolveAll(0x78b8880, {{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x0, 0x1, 0x0})
        /Users/runner/work/devspace/devspace/pkg/devspace/dependency/dependency.go:104 +0x85
github.com/loft-sh/devspace/cmd/reset.(*podsCmd).RunResetPods(0xc0006359e0, {0x5f1e838, 0x7913cf0}, 0xc00105fa18, {0xc00105f9f0, 0x0, 0x0})
        /Users/runner/work/devspace/devspace/cmd/reset/pods.go:100 +0x2cc
github.com/loft-sh/devspace/cmd/reset.newPodsCmd.func1(0xc00027d680, {0x7913cf0, 0x0, 0x0})
        /Users/runner/work/devspace/devspace/cmd/reset/pods.go:46 +0x3f
github.com/spf13/cobra.(*Command).execute(0xc00027d680, {0x7913cf0, 0x0, 0x0})
        /Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000278000)
        /Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:897
github.com/loft-sh/devspace/cmd.Execute()
        /Users/runner/work/devspace/devspace/cmd/root.go:119 +0x1e8
main.main()
        /Users/runner/work/devspace/devspace/main.go:20 +0xdd
```

**What did you expect to happen instead?**  

Dependencies being resolved without exceptions 😉 

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Not sure how to reproduce this on a minimal setup; my project setup has ~20 dependencies, some of which have dependencies of their own; I'm trying to figure out if there's one without a `name` property, but haven't found one yet. I'm happy to provide more info if needed; please let me know what would be useful.

**Local Environment:**  
- DevSpace Version: 5.18.0
- Operating System: mac

**Kubernetes Cluster:**  
- Cloud Provider: docker desktop (mac)
- Kubernetes Version: v1.22.4

**Anything else we need to know?**  

* Clearing `~/.devspace/dependencies` doesn't help; updating dependencies via `devspace update dependencies ` works fine

/kind bug

**Comment by pratikjagrut** [comment]
HI @bforchhammer thanks for creating this issue. Looks like cyclic dependency is breaking something there. We'll troubleshoot this and we'll fix it ASAP.

**Comment by nadavshatz** [comment]
thanks so much for the super quick handling everyone.
I see the fix got merged about 15m ago.

Don't want to be pushy but any chance to get a patch version or even a patch beta version out?

**Comment by FabianKramm** [comment]
@nadavshatz we just released DevSpace v5.18.1-beta.0 which includes the fix and should be available as soon as the pipeline has run through which is in about 20-30 minutes

**Comment by nadavshatz** [comment]
@FabianKramm amazing, thanks so much!

**Comment by nadavshatz** [comment]
FYI still having this error even with the new beta :(

**Comment by FabianKramm** [comment]
@nadavshatz yes we fixed this with #1827 which can occur in `devspace sync`, are you using this command outside of a devspace project folder?

**Comment by nadavshatz** [comment]
I was yes. I'll try the newer beta as well and update here if it worked

**Comment by nadavshatz** [comment]
Working great for me with 5.18.1-beta.1 🙏🏼

**Comment by bforchhammer** [comment]
Thanks for fixing this so quickly! ❤️ I'm not getting the `runtime error` anymore!
