### ISSUE TITLE
Inconsistent "help" behavior for commands provided by plugins.

### ISSUE THREAD

**Issue by matskiv** [loft-sh/devspace#1841]
**What happened?**  
Problems and inconsistencies of the "help" output for the for commands provided by plugins:
a) `devspace help` prints global flags for commands provided by plugins, but there is not guarantee that plugin command accepts these flags, or even worse, the same flag might have different meaning (e.g. `--config` flag for commands provided by loft plugin).
b) Plugin docs page states the following about the `usage` property of plugin `commands` - `the usage of the command to print in devspace --help`, but when you run `devspace some-plugin-cmd --help` the plugin binary prints the help information(if implemented) and `usage` property is ignored.
c) Different output of `devspace help some-plugin-cmd` and `devspace some-plugin-cmd --help`

**What did you expect to happen instead?**  
Don't print global flags for plugin commands (unless we introduce a plugin command property that would confirm that all global devspace flags are accepted)
Consider unifying the behavior (ensure same output) of both methods for getting help information and update the docs accordingly.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
```
devspace add plugin https://github.com/loft-sh/devspace-plugin-loft
devspace help use space
devspace use space --help
```

**Local Environment:**  
- DevSpace Version: 5.18.1
- Operating System: linux
- ARCH of the OS: AMD64

**Anything else we need to know?**  
devspace-plugin-loft version: v2.0.3

/kind bug

**Comment by FabianKramm** [comment]
@matskiv thanks for creating this issue! Yes thats problematic, we should disable the `devspace help` command completely as we do not know during plugin command registration which flags do exist for the plugin commands. `devspace help` is also not documented anywhere.
