### ISSUE TITLE
devspace commands including "devspace use space""devspace deploy" fail

### ISSUE THREAD

**Issue by yingqi1997** [loft-sh/devspace#1848]
What's the root cause for this error? I'm using latest kubernetes 1.23.1 , devspace 5.18.1

yding@CHENMS-yding f8-development-env-tools % devspace use space yingqi
panic: reflect.Set: value of type map\[interface {}\]interface {} is not assignable to type runtime.Object \[recovered\]
panic: reflect.Set: value of type map\[interface {}\]interface {} is not assignable to type runtime.Object

goroutine 1 \[running\]:
[gopkg.in/yaml.v2.handleErr(0xc000655988)](http://gopkg.in/yaml%2ev2.handleErr(0xc000655988))
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/gopkg.in/yaml.v2/yaml.go:249 +0x9a
panic(0x53f4de0, 0xc000727d60)
/Users/runner/hostedtoolcache/go/1.13.14/x64/src/runtime/panic.go:679 +0x1b2
reflect.Value.assignTo(0x544b9e0, 0xc0005ce720, 0x15, 0x57115a4, 0xb, 0x54c1580, 0xc000727d50, 0x544b9e0, 0x0, 0xc0005ce720)
/Users/runner/hostedtoolcache/go/1.13.14/x64/src/reflect/value.go:2411 +0x432
reflect.Value.Set(0x54c1580, 0xc000727d50, 0x194, 0x544b9e0, 0xc0005ce720, 0x15)
/Users/runner/hostedtoolcache/go/1.13.14/x64/src/reflect/value.go:1544 +0xbd
[gopkg.in/yaml.v2.(\*decoder](http://gopkg.in/yaml%2ev2.(\*decoder)).mapping(0xc0007086c0, 0xc0006056c0, 0x54c1580, 0xc000727d50, 0x194, 0x54c1580)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/gopkg.in/yaml.v2/decode.go:635 +0x90d
[gopkg.in/yaml.v2.(\*decoder](http://gopkg.in/yaml%2ev2.(\*decoder)).unmarshal(0xc0007086c0, 0xc0006056c0, 0x54c1580, 0xc000727d50, 0x194, 0x194)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/gopkg.in/yaml.v2/decode.go:372 +0x1af
[gopkg.in/yaml.v2.(\*decoder](http://gopkg.in/yaml%2ev2.(\*decoder)).mapping(0xc0007086c0, 0xc0006055e0, 0x5450a20, 0xc000611fe0, 0x195, 0x5450a20)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/gopkg.in/yaml.v2/decode.go:676 +0x48d
[gopkg.in/yaml.v2.(\*decoder](http://gopkg.in/yaml%2ev2.(\*decoder)).unmarshal(0xc0007086c0, 0xc0006055e0, 0x5450a20, 0xc000611fe0, 0x195, 0xc000611fe0)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/gopkg.in/yaml.v2/decode.go:372 +0x1af
[gopkg.in/yaml.v2.(\*decoder](http://gopkg.in/yaml%2ev2.(\*decoder)).mappingStruct(0xc0007086c0, 0xc000604fc0, 0x560aca0, 0xc000611f80, 0x199, 0xae000000052d5b01)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/gopkg.in/yaml.v2/decode.go:767 +0xa6c
[gopkg.in/yaml.v2.(\*decoder](http://gopkg.in/yaml%2ev2.(\*decoder)).mapping(0xc0007086c0, 0xc000604fc0, 0x560aca0, 0xc000611f80, 0x199, 0x560aca0)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/gopkg.in/yaml.v2/decode.go:626 +0xa94
[gopkg.in/yaml.v2.(\*decoder](http://gopkg.in/yaml%2ev2.(\*decoder)).unmarshal(0xc0007086c0, 0xc000604fc0, 0x549f500, 0xc000010b20, 0x196, 0x196)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/gopkg.in/yaml.v2/decode.go:372 +0x1af
[gopkg.in/yaml.v2.(\*decoder](http://gopkg.in/yaml%2ev2.(\*decoder)).mapping(0xc0007086c0, 0xc000636690, 0x544ebc0, 0xc000709530, 0x195, 0x544ebc0)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/gopkg.in/yaml.v2/decode.go:676 +0x48d
[gopkg.in/yaml.v2.(\*decoder](http://gopkg.in/yaml%2ev2.(\*decoder)).unmarshal(0xc0007086c0, 0xc000636690, 0x544ebc0, 0xc000709530, 0x195, 0xc000709530)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/gopkg.in/yaml.v2/decode.go:372 +0x1af
[gopkg.in/yaml.v2.(\*decoder](http://gopkg.in/yaml%2ev2.(\*decoder)).mappingStruct(0xc0007086c0, 0xc000636150, 0x5618020, 0xc000709500, 0x199, 0x5301f56)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/gopkg.in/yaml.v2/decode.go:767 +0xa6c
[gopkg.in/yaml.v2.(\*decoder](http://gopkg.in/yaml%2ev2.(\*decoder)).mapping(0xc0007086c0, 0xc000636150, 0x5618020, 0xc000709500, 0x199, 0x5618020)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/gopkg.in/yaml.v2/decode.go:626 +0xa94
[gopkg.in/yaml.v2.(\*decoder](http://gopkg.in/yaml%2ev2.(\*decoder)).unmarshal(0xc0007086c0, 0xc000636150, 0x5618020, 0xc000709500, 0x199, 0x0)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/gopkg.in/yaml.v2/decode.go:372 +0x1af
[gopkg.in/yaml.v2.(\*decoder](http://gopkg.in/yaml%2ev2.(\*decoder)).document(0xc0007086c0, 0xc0006360e0, 0x5618020, 0xc000709500, 0x199, 0x44a7450)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/gopkg.in/yaml.v2/decode.go:384 +0x7c
[gopkg.in/yaml.v2.(\*decoder](http://gopkg.in/yaml%2ev2.(\*decoder)).unmarshal(0xc0007086c0, 0xc0006360e0, 0x5618020, 0xc000709500, 0x199, 0x199)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/gopkg.in/yaml.v2/decode.go:360 +0x247
[gopkg.in/yaml.v2.unmarshal](http://gopkg.in/yaml%2ev2.unmarshal)(0xc00040c000, 0x8458, 0xa000, 0x5554d20, 0xc000709500, 0x0, 0x0, 0x0)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/gopkg.in/yaml.v2/yaml.go:148 +0x35d
[gopkg.in/yaml.v2.Unmarshal(...)](http://gopkg.in/yaml%2ev2.Unmarshal(...))
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/gopkg.in/yaml.v2/yaml.go:81
[github.com/devspace-cloud/devspace/pkg/devspace/config/versions/util.Convert](http://github.com/devspace-cloud/devspace/pkg/devspace/config/versions/util.Convert)(0x5369ce0, 0xc000011078, 0x5554d20, 0xc000709500, 0x180, 0x0)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/github.com/devspace-cloud/devspace/pkg/devspace/config/versions/util/convert.go:11 +0x83
[github.com/devspace-cloud/devspace/pkg/devspace/kubectl.NewClientFromContext](http://github.com/devspace-cloud/devspace/pkg/devspace/kubectl.NewClientFromContext)(0xc000493ab0, 0xf, 0x0, 0x0, 0xed96f4200, 0x59d7840, 0x673a678, 0xda17bac3, 0xc00060c330, 0xc000493dd0, ...)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/github.com/devspace-cloud/devspace/pkg/devspace/kubectl/client.go:89 +0xe4
[github.com/devspace-cloud/devspace-cloud-plugin/pkg/factory.(\*DefaultFactoryImpl](http://github.com/devspace-cloud/devspace-cloud-plugin/pkg/factory.(\*DefaultFactoryImpl)).NewKubeClientFromContext(0x673a678, 0xc000493ab0, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000626b70, 0xc000589c48)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/pkg/factory/factory.go:65 +0x78
[github.com/devspace-cloud/devspace-cloud-plugin/cmd/use.(\*spaceCmd](http://github.com/devspace-cloud/devspace-cloud-plugin/cmd/use.(\*spaceCmd)).RunUseSpace(0xc000186300, 0x59d77e0, 0x673a678, 0xc0001682c0, 0xc000281ab0, 0x1, 0x1, 0x0, 0x0)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/cmd/use/space.go:172 +0x78a
[github.com/devspace-cloud/devspace-cloud-plugin/cmd/use.newSpaceCmd.func1](http://github.com/devspace-cloud/devspace-cloud-plugin/cmd/use.newSpaceCmd.func1)(0xc0001682c0, 0xc000281ab0, 0x1, 0x1, 0x0, 0x0)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/cmd/use/space.go:45 +0x64
[github.com/spf13/cobra.(\*Command](http://github.com/spf13/cobra.(\*Command)).execute(0xc0001682c0, 0xc000281a90, 0x1, 0x1, 0xc0001682c0, 0xc000281a90)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/github.com/spf13/cobra/command.go:842 +0x460
[github.com/spf13/cobra.(\*Command](http://github.com/spf13/cobra.(\*Command)).ExecuteC(0xc0000eab00, 0x673a678, 0xc0000eab00, 0x594ca9d)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/github.com/spf13/cobra/command.go:950 +0x349
[github.com/spf13/cobra.(\*Command](http://github.com/spf13/cobra.(\*Command)).Execute(...)
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/vendor/github.com/spf13/cobra/command.go:887
[github.com/devspace-cloud/devspace-cloud-plugin/cmd.Execute()](http://github.com/devspace-cloud/devspace-cloud-plugin/cmd.Execute())
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/cmd/root.go:75 +0x75
main.main()
/Users/runner/work/devspace-cloud-plugin/devspace-cloud-plugin/main.go:17 +0x3e

**Comment by yingqi1997** [comment]
OS: mac

**Comment by FabianKramm** [comment]
@yingqi1997 thanks for creating this issue! How did you install the plugin, seems like you installed a broken plugin in DevSpace, you can delete the `~/.devspace/plugins` which should restore correct DevSpace functionality.

**Comment by yingqi1997** [comment]
@FabianKramm  removed ~/.devspace/plugins , and i reinstalled it using cmd line, same error

 devspace add plugin https://github.com/devspace-cloud/devspace-cloud-plugin
[info]   Installing plugin https://github.com/devspace-cloud/devspace-cloud-plugin
[done] √ Successfully installed plugin https://github.com/devspace-cloud/devspace-cloud-plugin
yding@CHENMS-yding plugins %
yding@CHENMS-yding plugins %
yding@CHENMS-yding plugins % devspace use space yingqi
panic: reflect.Set: value of type map[interface {}]interface {} is not assignable to type runtime.Object [recovered]
	panic: reflect.Set: value of type map[interface {}]interface {} is not assignable to type runtime.Object

**Comment by FabianKramm** [comment]
@yingqi1997 devspace cloud is deprecated and currently not maintained anymore, why do you need the devspace cloud plugin?
