### ISSUE TITLE
How can I replace multiple images in one pod?

### ISSUE THREAD

**Issue by johnnypea** [loft-sh/devspace#1875]
I have two containers in one pod and I would like to replace images in both of them during "dev". How can I do that?

I can't replace the same pod twice using any selector and I can't define multiple "replaceImage" with "containerName".

Thanks.

**Comment by LukasGentele** [comment]
You mean in replacePods? Besides replaceImage, it also supports `patches` that you can use to patch the spec. Does that answer your question?

**Comment by LukasGentele** [comment]
You mean in replacePods? Besides replaceImage, it also supports `patches` that you can use to patch the spec. Does that answer your question?

**Comment by johnnypea** [comment]
Yes. Do I understand it correctly replacePods works the same as if I patched it? Or is there any difference?

**Comment by FabianKramm** [comment]
@johnnypea its different in that `replacePods` will actually replace the whole pod, while profile patches will only replace parts of the config before deploying it. 

Regarding your question to replace multiple images in the same pod, you can do that via replaceImage and patches, however in patches, you are only able to reference a static image tag and not a dynamically built one

**Comment by johnnypea** [comment]
Thanks @FabianKramm , but I can still replace only one image in pod using `replaceImage`, right?

**Comment by LukasGentele** [comment]
@johnnypea Yes you can. You don't need profiles at all for this. You just need replacePods and the patches field that it has. See this example: https://devspace.sh/cli/docs/configuration/development/replace-pods#example-overwrite-command-and-args-of-a-pod

Instead of overwriting command and args, you can just overwrite the image for the container with index 1 (example uses container with index 0)

**Comment by LukasGentele** [comment]
Closing this since the questions is answered. Feel free to reopen if there is a need for further clarifications.
