### ISSUE TITLE
PATH env variable is rewritten with colon separators when executing commands on windows

### ISSUE THREAD

**Issue by markphillips100** [loft-sh/devspace#1878]
**What happened?**  
Trying to run a powershell script using `pwsh` or `powershell` as a command where the script has reference to an exe in path, only the PATH env is a series of paths concatenated with a colon rather than semi-colon.  As a result the exe is not found.

**What did you expect to happen instead?**  
The part of the path representing the original env PATH should remain unaltered by the devspace cli.  If the PATH env is not a valid set of semi-colon paths (on windows) then the script will be unable to access binaries in the path.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. Install Windows Powershell 7 https://github.com/PowerShell/PowerShell/releases to test the `pwsh` approach, else use `powershell` from regular windows.
2. Create a simple ps1 file with the following content in the same folder as the devspace.yaml:

```
Write-Host "Env: $Env:Path"
```

3. Run the script to ensure it works (assuming you have more than 1 path entry in your profile's PATH env else the test is moot).  From a windows powershell terminal (not a linux distro) type > `pwsh .\print-path.ps1` or `powershell -ep Bypass ./print-path.ps1`, depending on your flavour of powershell.  The path should be printed and show semi-colons as separators regardless of whether windows or cross-platform powershell is used.
4. Run the devspace command to have it run the same ps1 script.  From the same terminal, type > `devspace run print-path`.  NOTE: the paths are now separated by colons.

My devspace.yaml:
```
version: v1beta11
commands:
- name: print-path
  command: "pwsh ./print-path.ps1"
```

Also tried regular windows powershell and the same path transformation occurs:
```
version: v1beta11
commands:
- name: print-path
  command: "powershell -ep Bypass ./print-path.ps1"
```

**Local Environment:**  
- DevSpace Version: [use `devspace --version`] 5.18.2
- Operating System: windows 11
- ARCH of the OS: AMD64 | ARM64 | i386
**Kubernetes Cluster:**  
No cluster

/kind bug

**Comment by FabianKramm** [comment]
@markphillips100 thanks for creating this issue! Does this also happen if you run:
```
version: v1beta11
commands:
- name: print-path
  command: "pwsh"
  args: ["./print-path.ps1"]
```

As we are using an internal golang shell to execute the commands if there are no `args` specified, this might solve the problem.

**Comment by markphillips100** [comment]
Woohoo! Works a treat.  Thank you @FabianKramm .  Appreciate the super fast response too.
