### ISSUE TITLE
evicted pods are still showing up in the devspace commands

### ISSUE THREAD

**Issue by ansonlc** [loft-sh/devspace#1880]
**Is your feature request related to a problem?**
when a pod is evicted (not sure why the evicted pod didn’t get deleted after 24 h) we can still see it in the devspace enter or other commands (devspace logs etc.)

**Which solution do you suggest?**
can we add a filter to only run those commands against healthy pods? Or any way to delete evicted pods automatically?

**Which alternative solutions exist?**

**Additional context**

/kind feature

**Comment by FabianKramm** [comment]
@ansonlc thanks a lot for creating this issue! Yes that makes a lot of sense, we'll exclude evicted pods from showing up in `devspace` commands

**Comment by pratikjagrut** [comment]
@ansonlc this feature was released in [v5.18.3](https://github.com/loft-sh/devspace/releases/tag/v5.18.3) could you please try it out and close this issue or update this issue accordingly? Thank you.
