### ISSUE TITLE
show better logs for waiting init containers to finish

### ISSUE THREAD

**Issue by ansonlc** [loft-sh/devspace#1881]
**Is your feature request related to a problem?**
currently we just see `DevSpace is waiting, because Pod pod-7c9dd4cd7-h4cr9-xn7tp has status: Init:0/3`
and from loft UI we can see no logs in the init containers

**Which solution do you suggest?**
add `set -x` in the init containers command
Or improve the logging in the `devspace dev` session (this will be better solution)

**Which alternative solutions exist?**

**Additional context**

/kind feature

**Comment by FabianKramm** [comment]
@ansonlc thanks for creating this issue! What are these init containers doing, is printing the log worthy there or are those init containers added through the persist paths feature of DevSpace?
