### ISSUE TITLE
TLS without cert-manager in Component Chart

### ISSUE THREAD

**Issue by johnnypea** [loft-sh/devspace#1910]
I don't have cert-manager installed as I handle certificates in Caddy container. Can I use `tls` option without actually generating certificate? I need this to open port 443. Thank you.

```
ingress:
  tls: true
  rules:
  - host: my-static-host.test
```

Without `tls`

```
❯ kubectl get ingress
NAME   CLASS   HOSTS                 ADDRESS     PORTS   AGE
app    nginx   my-static-host.test   localhost   80      14m
```

With `tls`

```
❯ kubectl get ingress
NAME   CLASS   HOSTS                 ADDRESS     PORTS     AGE
app    nginx   my-static-host.test   localhost   80, 443   19m
```

**Comment by FabianKramm** [comment]
@johnnypea I'm not entirely sure if I understand this correctly, but ingresses only open up on port `443` when you specify a TLS section. We currently also don't require cert-manager, you also use your custom secret via:
```
ingress:
  tls: my-tls-secret
```

**Comment by johnnypea** [comment]
> Using tls: true requires that your Kubernetes cluster has cert-manager installed.

https://devspace.sh/component-chart/docs/guides/ssl-certificates

**Comment by LukasGentele** [comment]
@johnnypea Only if you set it to `true` but if you provide the value of a secret like @FabianKramm suggested with `tls: my-tls-secret`, you won't need cert-manager. We should clarify that more though in the docs.
