### ISSUE TITLE
Sync download/uploadExcludeFile parsing

### ISSUE THREAD

**Issue by kickthemooon** [loft-sh/devspace#2077]
When using either download or uploadExcludeFile under dev.sync\[\*\] with following `.gitignore` style entries

```
!/some/path/in/my/repo/
```

Devspace is complaining that `!/some/path/in/my/repo/` should be used instead of `!some/path/in/my/repo`.
But as you can see exactly that is used and when I use `excludePaths` instead of file the warnings disappear.

OS: Mac Catalina
Devspace: 5.18.4
K8s: 1.20

**Comment by FabianKramm** [comment]
@kickthemooon thanks for creating this issue! Did you maybe use it like this:
```yaml
- !/some/path/in/my/repo
```
Since `!` is a special character in yaml, you need to use instead:
```yaml
- "!/some/path/in/my/repo"
```

**Comment by kickthemooon** [comment]
> @kickthemooon thanks for creating this issue! Did you maybe use it like this:
> ```yaml
> - !/some/path/in/my/repo
> ```
> Since `!` is a special character in yaml, you need to use instead:
> ```yaml
> - "!/some/path/in/my/repo"
> ```

The issue is about excludeFile i. e. When using an external file with a list of gitignore style items.

The issue is not about the config yaml file. In the config yaml file using excludePaths and quotes around the items seema to work fine

**Comment by FabianKramm** [comment]
@kickthemooon ah yeah sorry, my bad. Yes you are correct, seems like the function we use internally cuts those leading `/` from the exclude paths. We'll issue a fix for this shortly

**Comment by FabianKramm** [comment]
@kickthemooon this should be fixed with the new v6 beta version, can you confirm this?
