### ISSUE TITLE
Cant switch profile if profiles are included via $(cat)

### ISSUE THREAD

**Issue by vladitot** [loft-sh/devspace#2087]
**What happened?**
I upgraded to 5.18.5. There is new feature: profiles can be described as includes via $(cat). It perfectly working, if you use **--profile** flag. But if you try call **devspace use profile local** - there is an error, says *profile is not found*. If I change it manually in .devspace/generated.yaml - profile changes.  If I try **devspace list profiles**, it says there is no entries found.

**What did you expect to happen instead?**
I expect, that profile is changing correctly to my "local" profile if it is included via $(cat), when I enter **devspace use profile local**

**How can we reproduce the bug?** (as minimally and precisely as possible)

My devspace.yaml:
<img width="515" alt="image" src="[https://user-images.githubusercontent.com/20747106/170647555-407dc367-b901-4aab-9cb4-56c7fd8f6e90.png](https://user-images.githubusercontent.com/20747106/170647555-407dc367-b901-4aab-9cb4-56c7fd8f6e90.png)">

```
version: 5.18.5, MacOS
...
```

**Local Environment:**

* DevSpace Version: 5.18.5
* Operating System:  mac
* ARCH of the OS: ARM64(M1)
  **Kubernetes Cluster:**
* Cloud Provider: Rancher-Desktop

**Anything else we need to know?**

/kind bug

**Comment by FabianKramm** [comment]
@vladitot thanks for reporting this issue! Seems like the cat is not correctly resolved on the `devspace use profile` command. We will fix that!

**Comment by FabianKramm** [comment]
@vladitot since this functionality will be removed in v6 I'm not sure if it's a good idea to fix that now

**Comment by FabianKramm** [comment]
We don't remove profiles completely, rather we remove the `devspace use profile` command as it makes DevSpace harder to understand if the profile is cached. In v6 (for which we will release docs very soon), we rather recommend to use pipelines and flags instead, although profiles still will work fine.

**Comment by vladitot** [comment]
Ok, when the docs will be ready? And when v6 release is planned?

**Comment by FabianKramm** [comment]
Docs should be ready on monday next week, and release will be in approx 2-3 Weeks
