### ISSUE TITLE
`devspace reset vars` doesn't accept config parameter

### ISSUE THREAD

**Issue by tompatib** [loft-sh/devspace#2094]
**What happened?**  
I have a monorepo with multiple projects and multiple DevSpace configs. I'm using the `--config devspace-projectX.yaml` for `devspace dev`, `devspace purge` and `devspace list vars`. Each works correctly.

When using the `devspace reset vars --config devspace-projectX.yaml` I get the following:

> [fatal]  Cannot find a devspace.yaml for this project. Please run `devspace init`

Same happens with each commands when not providing the --config parameter.

**What did you expect to happen instead?**  

The command should reset the related config file in the .devspace\generated-devspace-projectX.yaml file.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

- Create 2 devspace configs, devspace-a.yaml, devspace-b.yaml
- Run `devspace dev --config devspace-a.yaml` 
- Run `devspace dev --config devspace-b.yaml`
- `devspace list vars --config devspace-a.yaml`
- `devspace reset vars --config devspace-a.yaml` 

**Local Environment:**  
- DevSpace Version: 5.18.4
- Operating System: linux
- ARCH of the OS: AMD64

**Anything else we need to know?**  

When there is only one devspace config available the command works well with the --config parameter, as I think it falls back to the default, but in my case there is no "default".

/kind bug

**Comment by FabianKramm** [comment]
@tompatib thanks for reporting this issue! Yes that makes sense, we can add this to DevSpace

**Comment by FabianKramm** [comment]
@tompatib this should be fixed with the new v6 beta version, can you confirm this?

**Comment by tompatib** [comment]
@FabianKramm tested with my existing configs and works as expected. With a new devspace init (v2beta1) I had hard time to create variables, even though it was added. Keep learning. Thanks! 👍
