### ISSUE TITLE
including a , in an unquoted yaml value for a helm chart caused a warn and failure in deployment as incorrect values are presented

### ISSUE THREAD

**Issue by darkedges** [loft-sh/devspace#2097]
**What happened?**  
Failed to use helm values file and started using incorrect values for deployment into environment.

```
[warn]   Error reading from chart dev overwrite values E:\development\projects\forgerock\devops\values\environments\devspace\frim.yaml: yaml: line 20: did not find expected key
```

**What did you expect to happen instead?**  
Expected the devspace to exit with the issue, as this cause the deployment to continue and use incorrect values.

```
darkedges-frim-55f7b4d697-9xbmg                          0/1     Init:InvalidImageName   0               76s
Warning  InspectFailed   8s (x11 over 97s)  kubelet            Failed to apply default image tag "darkedges/frim:zKOpXkL:7.1.0-eval": couldn't parse image reference "darkedges/frim:zKOpXkL:7.1.0-eval": invalid reference format
```

**How can we reproduce the bug?** (as minimally and precisely as possible)  
include a `,` at the end of an non quoye yaml value

```
services:
  identity:
    details:
      username: "uid=am-identity-bind-account,ou=admins,ou=identities",
```

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@darkedges thanks for creating this issue! Yes we should print a fatal here, thanks for reporting!
