### ISSUE TITLE
component chart nfs support

### ISSUE THREAD

**Issue by Orgil** [loft-sh/devspace#2098]
**Is your feature request related to a problem?**
Currently component chart doesn't support nfs key when volumes are defined so containers cannot directly mount nfs share.

**Which solution do you suggest?**
add nfs section to component chart volumes section same as kubernetes.

**Which alternative solutions exist?**
as my understanding, only way to mount nfs is through storageclass.

**Additional context**

/kind feature

**Comment by FabianKramm** [comment]
@Orgil thanks for creating this issue! As the component chart shouldn't cover every use case and rather be a simple to use generic chart, you could also just create a separate chart or manifests to configure this. Would that be an option for you?
