### ISSUE TITLE
Bug: Devspace Init new .net 6 WebAPI chart in root of solution folder fails to find image tags

### ISSUE THREAD

**Issue by jariahh** [loft-sh/devspace#2104]
When running devspace init and following the prompts and selecting the chart directory, it fails with "fatal cannot ask question 'Which image do you want to develop with DevSpace?' because log level is too low"

I expected it to find an image and create my devspace.yaml

Here is a sample app:
[https://github.com/jariahh/TestApp](https://github.com/jariahh/TestApp)

Also ran it with --debug

`
fatal cannot ask question 'Which image do you want to develop with DevSpace?' because log level is too low
github.com/loft-sh/devspace/pkg/util/log.(*StreamLogger).Question
        /Users/runner/work/devspace/devspace/pkg/util/log/stream_logger.go:525
github.com/loft-sh/devspace/cmd.(*InitCmd).initDevspace
        /Users/runner/work/devspace/devspace/cmd/init.go:354
github.com/loft-sh/devspace/cmd.(*InitCmd).Run
        /Users/runner/work/devspace/devspace/cmd/init.go:160
github.com/loft-sh/devspace/cmd.NewInitCmd.func1
        /Users/runner/work/devspace/devspace/cmd/init.go:92
github.com/spf13/cobra.(*Command).execute
        /Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        /Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:974
github.com/spf13/cobra.(*Command).Execute
        /Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:902
github.com/loft-sh/devspace/cmd.Execute
        /Users/runner/work/devspace/devspace/cmd/root.go:134
main.main
        /Users/runner/work/devspace/devspace/main.go:20
runtime.main
        /Users/runner/hostedtoolcache/go/1.17.10/x64/src/runtime/proc.go:255
runtime.goexit
        /Users/runner/hostedtoolcache/go/1.17.10/x64/src/runtime/asm_amd64.s:1581
`

**Local Environment:**  
- DevSpace Version:devspace version 6.0.0-alpha.19
- Operating System: windows and ubuntu(WSL)
- ARCH of the OS: AMD64 | ARM64 | i386
**Kubernetes Cluster:**  
- Cloud Provider: google
- Kubernetes Version: v1.24.1

/kind bug

**Comment by FabianKramm** [comment]
@jariahh thanks for reporting this issue! We will take a look and issue a fix for this!

**Comment by FabianKramm** [comment]
@jariahh it seems to work fine for me, are you using the flag `--silent` or an environment variable that might set this by default?

**Comment by jariahh** [comment]
@FabianKramm I tried with --silent=false, same result, but I have to admit that I haven't tried it on any other machine. My work laptop seems to be pretty locked down. I'll try on my personal machine and get back to you.

**Comment by FabianKramm** [comment]
@jariahh okay thanks for the update, I'll try to reproduce once more on windows, maybe it behaves differently there
