### ISSUE TITLE
Deployments in v6 don't copy annotations from original ones

### ISSUE THREAD

**Issue by ninjaprox** [loft-sh/devspace#2118]
**What happened?**  

In Devspace v6, deployments are created from original ones without copying annotations. There're use cases we reply on annotations in deployments for different behaviors. Missing these annotations causes functions don't work properly.

**What did you expect to happen instead?**  

All annotations in original deployments should be copied to ones created by Devspace.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    example.com/k1: v1
    example.com/k2: v2
spec:
  ..
```

**Local Environment:**  
- DevSpace Version: devspace version 6.0.0-beta.0
- Operating System: mac
- ARCH of the OS: ARM64

**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:17:11Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@ninjaprox thanks for creating this issue! Yes we can add that.
