### ISSUE TITLE
Underscores no longer allowed in devspace commands in v6

### ISSUE THREAD

**Issue by rmcclaincf** [loft-sh/devspace#2132]
**What happened?**  
Upgraded to v6.  Underscores no longer allowed in devspace commands.  Switching it to dashes worked.

**What did you expect to happen instead?**  
Underscores allowed.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
```
commands:
- name: init_single_partition_topics
  command: ./kafka/init-topics.sh PARTITIONS=1 REPLICATION=1 TOPICS=db.al.predictions,db.builder.units,db.workflows.all.tables,db.workflows.datauploads,scriptsapi.transform.from.workflows.to.scriptsapi,wfp.processed.datalines.from.scripts,scriptsapi.transform.dead.letters.from.workflows,scriptsapi.transform.test.dead.letters,scriptsapi.transform.test.to.scriptsapi,scriptsapi.transform.test.from.scriptsapi,job.archive.commands
```

My devspace.yaml:
```
version: v1beta11
Rest not included.
...
```

**Local Environment:**  
- DevSpace Version: devspace version 6.0.0-beta.0

- 
- Operating System: mac

**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: [use `kubectl version`]
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10", GitCommit:"eae22ba6238096f5dec1ceb62766e97783f0ba2f", GitTreeState:"clean", BuildDate:"2022-05-24T12:49:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  
No

/kind bug

**Comment by FabianKramm** [comment]
@rmcclaincf thanks for creating this issue! Yes we can allow underscorces again for commands
