### ISSUE TITLE
Open multiple terminal for each dependency

### ISSUE THREAD

**Issue by sandrotaje** [loft-sh/devspace#2142]
**Is your feature request related to a problem?**
In our use case, we are using a monorepo that has a root devspace file with dependencies that points to subfolders

**Which solution do you suggest?**
I suggest, if it is feasible, opening multiple terminals, one for each dependency, to have a way to run a script at startup time and obviously to have the terminal of my container already opened as I would run `devspace dev` inside the dependency.

**Which alternative solutions exist?**
Currently, we are running `devspace dev` from the root devspace and then we added two commands to enter a specific dep running directly a command inside the container (ex. `npm start`)

/kind feature

**Comment by FabianKramm** [comment]
@sandrotaje thanks for creating this issue! Not sure if I understand you correctly, but you want to open multiple terminals from a single terminal? Not sure if that is actually possible as most users use devspace inside an IDE and the terminals are usually tabs that cannot be created directly in the IDE without any sort of plugin / extension. However, when we would create an IDE integration we could think about adding this feature.
