### ISSUE TITLE
Documentation for profiles is missing in the v6 docs

### ISSUE THREAD

**Issue by tobalsgithub** [loft-sh/devspace#2146]
**What happened?**
The "profiles" section is missing in the [v6 docs](https://devspace.sh/docs/configuration/reference).

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/d1260edd-58a7-48b4-afee-a37eeec3b5c3/cb41befb-d44f-42ca-b8ac-a42f0a6341ca)

**What did you expect to happen instead?**
So far it seems like profiles are still supported, so I would expect to see the profiles section in the docs.

/kind bug

**Comment by FabianKramm** [comment]
@tobalsgithub you are correct, we will add the documentation shortly. Since there were no real changes to profiles in v6, you can also take a look at the v5 profiles docs meanwhile
