### ISSUE TITLE
Roadmap required

### ISSUE THREAD

**Issue by thebsdbox** [loft-sh/devspace#2175]
**Is your feature request related to a problem?**  
No there is no existing problem, this is an addition to the project

**Which solution do you suggest?**  
Creation of a `roadmap.md`

**Which alternative solutions exist?**  
n/a

**Additional context**  
n/a

/kind feature

**Comment by LukasGentele** [comment]
Done https://github.com/loft-sh/devspace/blob/master/ROADMAP.md
