### ISSUE TITLE
A Maintainers file

### ISSUE THREAD

**Issue by thebsdbox** [loft-sh/devspace#2176]
**Is your feature request related to a problem?**  
No problem this is an addition to the repository

**Which solution do you suggest?**  
Addition of a CODEOWNERS file (https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
)

**Which alternative solutions exist?**  
N/A

**Additional context**  
N/A

/kind feature

**Comment by LukasGentele** [comment]
Done https://github.com/loft-sh/devspace/blob/master/CODEOWNERS
