### ISSUE TITLE
Update schema on schemastore.org

### ISSUE THREAD

**Issue by withinboredom** [loft-sh/devspace#2177]
**What happened?**  

Intellij pulls the schema from schemastore.org in order to provide code completion and assistance. The current schema there doesn't recognize version `v2beta1` and the IDE thinks everything is wrong.

**What did you expect to happen instead?**  

The schema to recognize `v2beta1` and either provide no assistance or updated to reflect the `v2beta1` schema.

/kind bug

**Comment by withinboredom** [comment]
> The current schema is added for v2beta1 only

Looking a little closer, I think maybe the schema definition might be off ... or the documentation.

Example in the documentation:

<img width="246" alt="image" src="https://user-images.githubusercontent.com/1883296/179345225-758675d5-f1a6-4af5-81cb-cf61b4b84a29.png">

From IDE:

<img width="377" alt="image" src="https://user-images.githubusercontent.com/1883296/179345264-fa90a029-0324-43e9-badb-c1c6f2db4310.png">

Example in the documentation:

<img width="387" alt="image" src="https://user-images.githubusercontent.com/1883296/179345378-d0ec5383-428c-49b5-a179-fdb7230aa0de.png">

From IDE:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/1883296/179345390-06dee851-048e-43ba-8ba9-fa26bf45b11a.png">

Documentation:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/1883296/179345438-0c38fd0c-2f6e-4a34-8121-e08e398b3df4.png">

From IDE:

<img width="359" alt="image" src="https://user-images.githubusercontent.com/1883296/179345467-a777a082-9563-42d5-b02b-eb73b8bec0d1.png">


Documentation:

<img width="258" alt="image" src="https://user-images.githubusercontent.com/1883296/179345577-a51bd1c1-60ba-4da6-a76f-c3ff68f238a8.png">


From IDE:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/1883296/179345485-6d230522-a45b-4c9a-ba25-ee7ee4161867.png">

**Comment by LukasGentele** [comment]
We have valid schema plus schema generator already in docs/hack and schema folder. I'll make sure we generate the newest version and submit to schemastore. Thanks for the contribution in hack/ on the root level but it's not producing the correct output. I'll make sure we get the official schema updated. @FabianKramm for reference not to accept any PRs on this topic since we already have a working script to produce a valid schema.

**Comment by dolfelt** [comment]
@LukasGentele @tukobadnyanoba It appears that the `devspace-schema.json` isn't a fully valid representation of the `devspace.yaml` schema. For example the `name` variable is required on `vars` and it doesn't recognize strings as a valid value. It seems that the generator isn't able to pick up on all the nuances built into the `UnmarshalYAML` methods. 

Is there a valid schema somewhere that can be used for development?

**Comment by FabianKramm** [comment]
@dolfelt not yet, but we will update that very shortly. The following tasks are left todo:
1. Allow string or object as value for vars, pipelines and commands (and all the others where we have an UnmarshalYAML method)
2. Remove the ./hack/genjsonschema implementation in favor of /[docs](https://github.com/loft-sh/devspace/tree/main/docs)/[hack](https://github.com/loft-sh/devspace/tree/main/docs/hack)/[config](https://github.com/loft-sh/devspace/tree/main/docs/hack/config)/schemas/ implementation
3. Remove the json spec description annotations in the devspace latest version
4. Update the jsonschema in the schemastore.org
