### ISSUE TITLE
devspacehelper does not work in Rancher Desktop 1.5.0

### ISSUE THREAD

**Issue by dhruvbaldawa** [loft-sh/devspace#2210]
**What happened?**  
I am using devspace 5.18.5 on Rancher Desktop 1.5.0 on Macbook Pro M1. When I run `devspace dev`, I see this output when trying to sync files.

```
[done] √ Done processing image 'myapp'
[info]   Execute 'helm upgrade myapp --namespace local --values /var/folders/ng/h__xfqys7pd6dl39ltk409s40000gn/T/4078936263 --install component-chart --repo https://charts.devspace.sh --repository-config='' --version 0.8.4 --kube-context rancher-desktop'
[done] √ Deployed helm chart (Release revision: 4)
[done] √ Successfully deployed myapp with helm

#########################################################
[info]   DevSpace UI available at: http://localhost:8090
#########################################################

[0:sync] Waiting for containers to start...
[0:sync] Starting sync...
[0:sync] Trying to download devspacehelper into pod local/myapp-7c7ffcdcc9-64ftp
[0:sync] Warning: Couldn't download devspacehelper in container, error: devspacehelper(DevSpace Utility CLI

Usage:
  devspacehelper [command]

Available Commands:
  completion  generate the autocompletion script for the specified shell
  help        Help about any command
  restart     Restarts the container if the restart helper is present
  sync        Sync holds the sync relevant commands
  tunnel      Starts a new tunnel for reverse port forwarding
  version     Prints the cli version

Flags:
  -h, --help   help for devspacehelper

Use "devspacehelper [command] --help" for more information about a command.
) and devspace(v5.18.5) differs in version
[0:sync] Trying to inject devspacehelper from local machine
[0:sync] Successfully injected devspacehelper into pod local/myapp-7c7ffcdcc9-64ftp
[0:sync] Start syncing
[0:sync] Sync started on /Users/dhruv/Projects/myapp <-> /usr/local/myapp (Pod: local/myapp-7c7ffcdcc9-64ftp)
[0:sync] Waiting for initial sync to complete
[0:sync] Error: Sync Error on /Users/dhruv/Projects/myapp: Sync - connection lost to pod local/myapp-7c7ffcdcc9-64ftp:  command terminated with exit code 135
[0:sync] Sync stopped
[fatal]  start sync: initial sync: Sync - connection lost to pod local/myapp-7c7ffcdcc9-64ftp:  command terminated with exit code 135
```

If I downgrade and go back to Rancher Desktop 1.4.x, this works fine without any other change. I tried upgrading to 1.5.0, and it failed again, and downgrading to 1.4.x fixed the issue with all other things being the same.

I understand that this could be an issue with Rancher Desktop, but I'd like to understand if you have any suspicions about what the issue could be?
 
**What did you expect to happen instead?**  

`devspace dev` to just work seamlessly on Rancher Desktop 1.5.0

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Use Rancher Desktop 1.5.0 on M1 Macbook Pro, run `devspace dev` on a project and it should fail at the file sync step. Going back to version 1.4.x should fix the issue.

**Local Environment:**  
- DevSpace Version: 5.18.5
- Operating System: mac
- ARCH of the OS: ARM64
**Kubernetes Cluster:**  
- Cloud Provider: k3s on Rancher Desktop
- Kubernetes Version: v1.22.5+k3s2

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@dhruvbaldawa thanks for reporting this issue! It works for me with the new DevSpace v6 version, can you try it with that version?

**Comment by dhruvbaldawa** [comment]
Figured out that it is related to https://github.com/rancher-sandbox/rancher-desktop/issues/2659
