### ISSUE TITLE
CODEOWNERS references unknown users

### ISSUE THREAD

**Issue by thebsdbox** [loft-sh/devspace#2211]
[https://github.com/loft-sh/devspace/blob/2c211c1b6db2c3b28861213a9a3fe89909e10261/CODEOWNERS#L1](https://github.com/loft-sh/devspace/blob/2c211c1b6db2c3b28861213a9a3fe89909e10261/CODEOWNERS#L1)

**Comment by thebsdbox** [comment]
`@loft-sh/devspace-maintainers` is apparently an unknown user, this can be seen when opening the `CODEOWNERS` file in GitHub.

**Comment by LukasGentele** [comment]
@FabianKramm Please revert these changes. The UI error is just displaying the wrong information. Instead of changing the CODEOWNERS file, we actually need to add the team to the GH repo for the error to disappear. For context:

```
It looks like you've set up the CODEOWNERS file correctly, but I believe the issue you're having is down to team permissions.
Teams are only requested for a review on a pull request when they have write access to the repository on the team itself. It's not enough for all the members to have write access, you need to grant write access to the actual team.


https://help.github.com/articles/managing-team-access-to-an-organization-repository/


Once you do this all future pull requests that involve files owned by that team should be automatically requested for a review.
```

Source: https://github.com/orgs/community/discussions/22751
