### ISSUE TITLE
Documentation entry for SSH and persistPaths are swapped

### ISSUE THREAD

**Issue by dhruvbaldawa** [loft-sh/devspace#2218]
**What happened?**  

Online documentation for `ssh` and `persistPaths` are swapped
<img width="896" alt="image" src="https://user-images.githubusercontent.com/380197/184521685-ab4017cb-83b8-4c4b-bf57-e72526b15ead.png">
<img width="889" alt="image" src="https://user-images.githubusercontent.com/380197/184521701-859e010c-4f42-4302-a365-eb65089a168d.png">

**Local Environment:**  
- DevSpace Version: [use `devspace --version`]
- Operating System: windows | linux | mac
- ARCH of the OS: AMD64 | ARM64 | i386
**Kubernetes Cluster:**  
- Cloud Provider: google | aws | azure | other
- Kubernetes Version: [use `kubectl version`]

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@dhruvbaldawa thanks for reporting this issue! You are correct, we need to change that

**Comment by FabianKramm** [comment]
@dhruvbaldawa should be fixed now
