### ISSUE TITLE
absolute paths and environment variables in file sync

### ISSUE THREAD

**Issue by AlexanderSarson** [loft-sh/devspace#2221]
**Is your feature request related to a problem?**  
no

**Which solution do you suggest?**  
It would be great if you could use absolute paths and environment variables when you file sync on Windows.

**Which alternative solutions exist?**  
Move all your settings and code projects into devspace or using "../../"

**Additional context**  
I want to use this for when you want to sync files such as .m2/settings, .npmrc or you already have an existing folder containing all your code projects

/kind feature

**Comment by FabianKramm** [comment]
@AlexanderSarson thanks for creating this issue! You should be able to use an absolute path for file syncing already, could you make an example where this doesn't work?

**Comment by AlexanderSarson** [comment]
@FabianKramm it's when you use something like this where you got two colons.
sync:
    - path: C:/codeproject:/home/dev/codeproject

**Comment by FabianKramm** [comment]
@AlexanderSarson oh, you are right, we can definitely fix this!
