### ISSUE TITLE
Variables in import paths are not resolved

### ISSUE THREAD

**Issue by dhruvbaldawa** [loft-sh/devspace#2233]
**What happened?**
If I use a variable in the path for `imports`, it is not resolved. I tried replacing it with a command variable too but it did not work.

**What did you expect to happen instead?**
I expect the variable to resolve correctly

**How can we reproduce the bug?** (as minimally and precisely as possible)

My devspace.yaml:

```
version: v2beta1
name: myapp
imports:
  - path: $(echo "${MY_CONF_DIR}/common")
```

On running `devspace print`

```
fatal read import config: open /path/to/dir/$(echo "${MY_CONF_DIR}/common")/devspace.yaml: no such file or directory
```

**Local Environment:**

* DevSpace Version: 6.0.0-beta.10
* Operating System: mac
* ARCH of the OS: ARM64
  **Kubernetes Cluster:**
* Cloud Provider: k3s
* Kubernetes Version: 1.22.5

**Anything else we need to know?**

/kind bug

**Comment by FabianKramm** [comment]
@dhruvbaldawa thanks for creating this issue! Yes that is currently intended as variables are resolved *after* imports are applied. The only place where variables can be used is `imports.*.enabled` right now.
