### ISSUE TITLE
Line numbers for invalid files are incorrect

### ISSUE THREAD

**Issue by ethankhall** [loft-sh/devspace#2246]
**What happened?**  

Running `devspace print` with an invalid file gives incorrect line numbers.

```
> devspace print
fatal error loading config: yaml: unmarshal errors:
  line 2: cannot unmarshal an array into map[string]*latest.CommandConfig (line 2: - command: |)
  line 199: cannot unmarshal an array into map[string]*latest.DependencyConfig (line 199: - name: deps)
  line 209: cannot unmarshal an array into map[string]*latest.DeploymentConfig (line 209: - helm:)
  line 233: field disabled not found in type latest.DevPod (line 233: disabled: true)
  line 235: cannot unmarshal an array into latest.DevPod (line 235: - url: http://fake:4001)
  line 237: cannot unmarshal an array into latest.DevPod (line 237: - forward:)
  line 251: cannot unmarshal an array into latest.DevPod (line 251: - containerName: rails)
  line 370: field build not found in type latest.Image (line 370: build:)
```

**What did you expect to happen instead?**  

The line numbers to match with the file on disk

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
```
version: v2beta1
name: fake
command:
 - name: foo
   command: env
```

**Local Environment:**  
- DevSpace Version: 6.0.0
- Operating System: mac
- ARCH of the OS: ARM64

/kind bug

**Comment by FabianKramm** [comment]
@ethankhall thanks for the issue! Unfortunately we cannot preserve the ordering of the keys when the DevSpace yaml is converted, but we'll print the parsed config including line numbers alongside the error in future which should make it a lot easier to see the problematic fields!
