### ISSUE TITLE
Shell formatting incorrect when "entering" from a function.

### ISSUE THREAD

**Issue by ethankhall** [loft-sh/devspace#2270]
**What happened?**  

When running a script from within a function that does a `devspace enter` causes the output to incorrect on newlines

```
> devspace run-pipeline testing 
info Using namespace 'ethan-hall'
info Using kube context 'loft_ethan-hall_portland'
bin   dev  home  lib32  libx32  mnt  proc  run   srv  tmp  var
                                                              boot  etc  lib     lib64  media   opt  root  sbin  sys  usr
                                                                                                                         %
```

**What did you expect to happen instead?** 
The newlines to start at the edge of the terminal. Running the enter command directly works correctly.

```
> devspace enter --silent -c rails -- ls /
bin   dev  home  lib32  libx32  mnt  proc  run   srv  tmp  var
boot  etc  lib   lib64  media   opt  root  sbin  sys  usr
```

**How can we reproduce the bug?**

My devspace.yaml:
```
version: v2beta1
functions:
  testing: |-
    bash -c 'devspace enter -c rails -- ls /'
pipelines:
  testing: |-
    testing
```

**Local Environment:**  
- DevSpace Version: devspace version 6.0.1
- Operating System: mac
- ARCH of the OS: ARM64 |
- *Kubernetes Cluster:**  
- Cloud Provider: aws 

**Anything else we need to know?** 

It looks like the `function shell` is emulating windows, and because there is no `\r` it's not resetting the cursor to the beginning of line.

Full output

```
> devspace run-pipeline testing 
info Using namespace 'ethan-hall'
info Using kube context 'loft_ethan-hall_portland'
bin   dev  home  lib32  libx32  mnt  proc  run   srv  tmp  var
                                                              boot  etc  lib     lib64  media   opt  root  sbin  sys  usr
                                                                                                                         %
> devspace enter --silent -c rails -- ls /
bin   dev  home  lib32  libx32  mnt  proc  run   srv  tmp  var
boot  etc  lib   lib64  media   opt  root  sbin  sys  usr
```

/kind bug

**Comment by lizardruss** [comment]
I'm looking into this issue, however for this specific case you can also use `exec_container`:
```yaml
version: v2beta1
functions:
  testing: |-
    exec_container --image-selector [IMAGE] --container [CONTAINER] -- ls -al /
pipelines:
  testing: |-
    testing
```

Currently with this approach, you'd need to pass either `--image-selector` or `--label-selector` flags in addition to `--container`

**Comment by FabianKramm** [comment]
@ethankhall thanks for reporting this! Seems like `devspace enter` acts as if the stdin is a terminal, so we need to check that.
