### ISSUE TITLE
Pull Secret creation fails with Azure Container Registry when using az cli for login

### ISSUE THREAD

**Issue by andrstor** [loft-sh/devspace#2278]
**What happened?**  
When using recommended login to Azure Container Registry:

```
az login
az acr login -n <registry>
```
the entry in .docker/config.json is not accepted by devspace when using the [Pull Secrets capability](https://devspace.sh/docs/configuration/pullSecrets/?x0=2). 

Running
```
devspace deploy
```
does not create a pull-secret. After printing "Ensuring image pull secret for registry:", the create part never happens.

If we instead use the Azure Container Registry admin account for login:

```
docker login <acr> --username <adminaccount>--password <passord>
```
This works as expected when deploying with devspace:
```
pullsecret:helsenorge Ensuring image pull secret for registry: 
pullsecret:helsenorge Created image pull secret dev/devspace-pull-secrets
```
The difference between the .docker/config.json
az acr login:
```json
{
	"auths": {
		"<>.azurecr.io": {
			"auth": "...",
			"identitytoken":"..."
		}
	}
}
```
docker login with admin account
```json
{
	"auths": {
		"<>.azurecr.io": {
			"auth": "..."
		}
	}
}
```

**What did you expect to happen instead?**  
Logging in with ``az acr login`` with your private account should work in the same way as logging in with an admin account. It should atleast give a clear error message about why the secret was not created.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
- Use acr as container registry and login to this with ``az acr login``
- Setup pull-secret in devspac.yaml targeting acr
- Run ``devspace deploy`` and see that no "devspace-pull-secrets" is created and no error messages are printed.

My devspace.yaml:
```yaml
pullSecrets:
  helsenorge:
    registry: <>.azurecr.io
```

**Local Environment:**  
- DevSpace Version: devspace version 6.0.1
- Operating System: windows 
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Same behaviour in KIND locally and Azure AKS
- Kubernetes Version: 
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a35ccc8395e8a5eaa83b7b8c981677893b651cba", GitTreeState:"clean", BuildDate:"2022-07-28T20:52:46Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@andrstor thanks for creating this issue! We'll investigate this and issue a fix for one of the next releases
