### ISSUE TITLE
`devspace use profile [profile]` not working

### ISSUE THREAD

**Issue by hariprasadiit** [loft-sh/devspace#2313]
**What happened?**  
`devspace use profile [profile]` is not available in cli, but mentioned in the docs

**What did you expect to happen instead?**  
`devspace use profile [profile]` command to work

**How can we reproduce the bug?** (as minimally and precisely as possible)  
try using `devspace use profile [profile]`

My devspace.yaml:
```
version: 2beta1
...
```

**Local Environment:**  
- DevSpace Version: v6.1.1
- Operating System: mac
- ARCH of the OS: AMD64

/kind bug

**Comment by FabianKramm** [comment]
@hariprasadiit thanks for creating this issue! Yes the command got removed from v5 to v6, so we will also remove it in the docs.

**Comment by shaunc** [comment]
Does this mean, to use a profile, we always have to specify it explicitly for every command?
