### ISSUE TITLE
UI - Different Running and Completed status indication

### ISSUE THREAD

**Issue by Andrioden** [loft-sh/devspace#2331]
**Is your feature request related to a problem?**  

No

**Which solution do you suggest?**  

I love DevSpace ui, the visualization of the kubernetes cluster's containers is great. However, i often find myself temporarily confused by wheter or not something is actually running or completed. I would argue it is important to quickly see that something is running and using resources.

The current Running green color is good.

Suggestions for the Completed status:
- A) Blue
- B) Dark Green
- C) Green as today, but with a gray thick border

![image](https://user-images.githubusercontent.com/393376/191475453-3157ba97-9218-4654-b76b-7b72707d0c7e.png)

/kind feature

**Comment by FabianKramm** [comment]
@Andrioden thanks for the issue! I see, so we should essentially use a different color for completed! We'll add this to the next release!
