### ISSUE TITLE
Cannot run devspace inside a docker instance

### ISSUE THREAD

**Issue by fuhengwu2021** [loft-sh/devspace#2333]
**What happened?**  
I want to use devspace to build a docker image inside a docker instance, but it doesn't work.

**What did you expect to happen instead?**  
devspace can build docker image inside docker instance

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Just run devspace deploy inside a running docker instance

/kind bug

**Comment by carlmontanari** [comment]
Hey there @fuhengwu2021 

I think probably it would be good to first understand what you are trying to accomplish?

If you are wanting to build an image from inside a container using *docker* specifically, you'll need to mount the docker sock in the container (searching docker-in-docker should give you a bunch of info on that).

If you just want to run devspace from the container and build images on your machine you can use devspace proxy commands as outlined [here](https://devspace.sh/docs/configuration/dev/connections/proxy-commands).

But, my guess is more that you are wanting to build the image in whatever cluster you are running in, you can do this with [kaniko](https://github.com/GoogleContainerTools/kaniko) -- [here](https://devspace.sh/docs/configuration/images/build-engines/kaniko) is the relevant section in our docs.

Let us know if that helps, or if not, please clarify and snag some logs/output and your devspace.yaml so we can better understand what is going on.
