### ISSUE TITLE
Windows install documentation info box is wrong

### ISSUE THREAD

**Issue by Andrioden** [loft-sh/devspace#2338]
The box i have crossed over contains information that is wrong.

The powershell comand `[Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::User);` is permanent.

Ref: https://stackoverflow.com/a/2571200/686131

I suggest you just remove the whole teal-colored info box.

![image](https://user-images.githubusercontent.com/393376/191951379-a1ccc3d7-b3a0-4b22-b9c7-a048bfd920b1.png)

**Comment by lizardruss** [comment]
Hello! Thanks for pointing this out. This was my experience as well. I'll create a PR to remove this section.
