### ISSUE TITLE
Devspace 6 resolves dependency variables regardless of v1beta11 disabled flag

### ISSUE THREAD

**Issue by lizardruss** [loft-sh/devspace#2352]
**What happened?**  
Given a `v1beta11` schema that utilizes `dependency.disabled` to enable or disable a dependency, the upgraded `v2beta1` schema no longer has the `disabled` flag, and devspace will download all dependencies in order to resolve variables. This can cause issues in CI when the environment does not have credentials to perform `git clone`

**What did you expect to happen instead?**  
Downloading the dependencies should be skipped

**How can we reproduce the bug?**

My devspace.yaml:
```
version: v1beta11
vars:
- name: DEP1_DISABLED
  default: false
deployments:
- name: nginx1
  helm:
    componentChart: true
    values:
      containers:
      - image: nginx
dependencies:
  - name: dep1
    disabled: ${DEP1_DISABLED}
    source:
      git: https://github.com/doesntexist/youcantcloneme
```

```sh
> devspace deploy --var DEP1_DISABLED=true
...
warn Error cloning or pulling git repository https://github.com/doesntexist/youcantcloneme: Error running 'git clone https://github.com/doesntexist/youcantcloneme /Users/russellcentanni/.devspace/dependencies/https-github-com-doesntexist-youcantcloneme --depth 1': error executing 'git clone https://github.com/doesntexist/youcantcloneme /Users/russellcentanni/.devspace/dependencies/https-github-com-doesntexist-youcantcloneme --depth 1':  -> Cloning into '/Users/russellcentanni/.devspace/dependencies/https-github-com-doesntexist-youcantcloneme'...
remote: Repository not found.
fatal: repository 'https://github.com/doesntexist/youcantcloneme/' not found

fatal deploy dependencies: resolve dependencies: loading config for dependency dep1: Couldn't load '/Users/russellcentanni/.devspace/dependencies/https-github-com-doesntexist-youcantcloneme/devspace.yaml': stat /Users/russellcentanni/.devspace/dependencies/https-github-com-doesntexist-youcantcloneme/devspace.yaml: no such file or directory
```

**Local Environment:**  
- DevSpace Version: 6.1.1
- Operating System: mac
- ARCH of the OS: ARM64
**Kubernetes Cluster:**  
- Cloud Provider: N/A
- Kubernetes Version: v1.25.1

**Anything else we need to know?**  
Using `--skip-dependency dep1` is a workaround.

Users encountered a different error than the above example, but the root cause of resolving dependency variables when they should be disabled is the same.

/kind bug

**Comment by FabianKramm** [comment]
@lizardruss thanks for the issue! Mhhh I guess we need to bring the flag back as its also useful for other use cases
