### ISSUE TITLE
Require should be added to ImportSections to allow recursive requirement checks

### ISSUE THREAD

**Issue by dtomasi** [loft-sh/devspace#2353]
**Is your feature request related to a problem?**  
Yes. I'm trying to create a library of reusable devspace components that can be used for different project across the company. My goal is for example to create a common setup for all golang projects and import all the required components to keep the devspace.yaml within the projects as small as possible. This is to avoid to have to apply changes to similar projects one by one. While I was setting up things, I noticed that `require` is not imported recursive. To me this is some kind of important, as I want to define the requirements in the different components, that are using different commands and plugins.

**Which solution do you suggest?**  
I suggest to add `require` to the imported fields list here: https://github.com/loft-sh/devspace/blob/main/pkg/devspace/config/loader/imports.go#L17
I already prepared a Pull-Request for that. Which I will reference to this issue soon.

**Which alternative solutions exist?**  

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
@dtomasi thanks for creating this issue! Yes we can do that and thanks for the PR!
