### ISSUE TITLE
Devspace 6 does not respect .env DEVSPACE_FLAGS

### ISSUE THREAD

**Issue by mnpenner** [loft-sh/devspace#2356]
**What happened?**  

I have a `.env` file in the root of my project directory. It contains

```
DEVSPACE_FLAGS="--kube-context=docker-desktop --namespace=mynamespace--profile development"
```

This used to work in 5.x, now when I run `devspace dev` it asks me what namespace to use despite having specified it there.

**What did you expect to happen instead?**  

Don't ask me what namespace to use when provided via `.env` file.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

I don't think the whole devspace.yaml file is relevant, but I'm using version `v2beta1`.

Create a `.env` file as described above, run `devspace dev`

**Local Environment:**  
- DevSpace Version: 6.1.1
- Operating System: windows-ish. Devspace and Docker are installed on Windows, but I run devspace.exe via WSL/Ubuntu
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Cloud Provider: Docker Desktop.
- Kubernetes Version: Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:26:51Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.10", GitCommit:"7e54d50d3012cf3389e43b096ba35300f36e0817", GitTreeState:"clean", BuildDate:"2022-08-17T18:26:59Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  

/kind bug

**Comment by lizardruss** [comment]
Hello! Thanks for using DevSpace!

In DevSpace 5, the `.env` file was implicitly loaded, but in DevSpace 6 it requires [additional configuration](http://localhost:3000/docs/configuration/variables#devspace_env_file-for-env-file-definition):
```yaml
vars:
  DEVSPACE_ENV_FILE: ".env"
```

Using a `v1beta11` schema with DevSpace 6 will have this configuration added to avoid breaking changes, however because you're using `v2beta1` it wasn't added automatically.

Let us know if that resolves your issue 👍

**Comment by alexandradragodan** [comment]
Hello, @mnpenner !

Thanks again for bringing this issue to our attention. 
Does the suggested configuration change(@lizardruss 's comment above) solve the issue for your desired use case? 

We would be grateful if you could provide us with an update as we want to quickly react to reported issues and keep our products as clean!

**Comment by mnpenner** [comment]
Hi! Sorry, missed lizardruss's response earlier. I haven't had a chance to test this yet, but that sounds like what I was looking for. I'm having another issue with 6.x that I need to figure out before I can switch back to that branch. I think we can close this ticket as resolved though 😊

PS @lizardruss, your link points to localhost 😀
