### ISSUE TITLE
Deploy with `--max-concurrent-builds` or `--build-sequential` does not apply to concurrent dependency builds

### ISSUE THREAD

**Issue by gustaff-weldon** [loft-sh/devspace#2380]
**What happened?**
I have a monorepo with API gateway. The gateway project depends on multiple service projects. Each project, including gateway, has at least one image to build.

When I run either `devspace deploy --build-sequential` or `devspace deploy --max-concurrent-builds 1` , devspace kicks off builds for mulitiple dependency projects at once, resulting in heavy parallelism, high memory usage by docker and recurring build failures.

**What did you expect to happen instead?**
I expected both `devspace deploy --build-sequential` and `devspace deploy --max-concurrent-builds 1` to kick off 1 build at a time. I would like developers to choose concurrency with `devspace deploy --max-concurrent-builds X`,  to control CPU load and memory usage on their machine.

**How can we reproduce the bug?** (as minimally and precisely as possible)
I have prepared a reproduction repo, just follow the steps from the readme.

[https://github.com/gustaff-weldon/devspace-build-concurrency](https://github.com/gustaff-weldon/devspace-build-concurrency)

**Local Environment:**

* DevSpace Version: 6.1.1
* Operating System: mac
* ARCH of the OS: x86_64

**Kubernetes Cluster:**

* local Docker Desktop cluster, but builds happen outside of it

**Anything else we need to know?**

/kind bug

**Comment by FabianKramm** [comment]
Hello @gustaff-weldon ! Thanks for creating this issue, right now the flag only applies to images within a single `devspace.yaml` and having this coordinated across dependencies is currently not supported. As a workaround you can deploy dependencies sequentially, like this:
```
pipelines:
  dev: |-
    run_dependencies --all --sequential
    ensure_pull_secrets --all
    build_images --all
    create_deployments --all
    start_dev --all
```

**Comment by alexandradragodan** [comment]
Hello, @gustaff-weldon ! 

Thanks again for reporting this issue! 
We will look into it and analyse if it makes sense for us to add such a feature. 

Obviously, we'll come back and let you know! 
Let's keep in touch!
