### ISSUE TITLE
devspace UI behind SSL proxy?

### ISSUE THREAD

**Issue by alexgorbatchev** [loft-sh/devspace#2407]
I'm running devspace UI behind SSL proxy, however functionality such as commands and terminal doesn't work due to `Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS` error. I tried to search the docs for an option/setting however didn't find anything.

Is it possible to run devspace UI behind SSL proxy?

**Comment by lizardruss** [comment]
Hello! Yes it looks like we assume this would be used locally without https / wss. Are you also loading the UI pages over https? If so, then this should be something we can detect and not require a configuration option.

**Comment by alexgorbatchev** [comment]
Yes, the UI is loaded via https as well.

**Comment by lizardruss** [comment]
OK thanks! We will release a fix for this soon.

**Comment by alexgorbatchev** [comment]
Thank you! <3
