### ISSUE TITLE
devspace sync usage out-of-date

### ISSUE THREAD

**Issue by baflo** [loft-sh/devspace#2430]
**What happened?**
The usage text of `devspace sync -h` seems to be out-of-date.

[https://github.com/loft-sh/devspace/blob/12530f9b582c11837808ad5719960e677b8f5423/cmd/sync.go#L65-L77](https://github.com/loft-sh/devspace/blob/12530f9b582c11837808ad5719960e677b8f5423/cmd/sync.go#L65-L77)

**What did you expect to happen instead?**
Correct usage examples.

**Comment by alexandradragodan** [comment]
Hey, @baflo . 

Thanks a lot for reporting this issue. 
We're currently looking into it!

Keep you posted! 🙌

**Comment by alexandradragodan** [comment]
Actually, What DevSpace version are you using? 

Could you provide a few more details?

Thanks!
