### ISSUE TITLE
LGPL licensed dependency

### ISSUE THREAD

**Issue by cjellick** [loft-sh/devspace#2467]
**What happened?**
Just a heads up that this dependency in your go.mod is LGPL licensed: [github.com/juju/ratelimit](http://github.com/juju/ratelimit)
Not sure if that matters to you, just wanted to call it out since this project is Apache licensed.

**Comment by FabianKramm** [comment]
@cjellick thanks a lot for reporting this issue! Yes we will remove that ASAP
