### ISSUE TITLE
Section commands such as devspace run [command] do not work when the k8s cluster is unavailable

### ISSUE THREAD

**Issue by atovstonog** [loft-sh/devspace#2470]
**What happened?**
Section commands such as devspace run \[command\] do not work when the k8s cluster is unavailable.
And when the k8s cluster was stopped or unavailable, we can't run the devspace commands and get an error:
`fatal error trying to load remote cache from current context and namespace: Get "https://0.0.0.0:49711/api/v1/namespaces/dev/secrets/devspace-cache-sb": dial tcp 0.0.0.0:49711: connect: connection refused `
Latest devspace version when it works - 6.1.0
Link to a recent fix ([https://github.com/loft-sh/devspace/pull/2429](https://github.com/loft-sh/devspace/pull/2429)) for another issue that requires a working cluster.

**What did you expect to happen instead?**
The command can be run when the cluster is unavailable

**How can we reproduce the bug?** (as minimally and precisely as possible)
Install version >6.1.0
stop local cluster like k3d
try to execute command, like `devspace run [command]`

My devspace.yaml:

```
version: v2beta1

require:
  devspace: 6.1.0
...
commands:
  cluster_stop:
    command: |-
      devspace run destroy
      k3d cluster stop dev
    section: environment
  cluster_start:
    command: |-
      k3d cluster start dev
      devspace run dev
    section: environment
```

**Local Environment:**

* DevSpace Version: >6.1.0
* Operating System: mac
* ARCH of the OS: AMD64 | ARM64 | i386
  **Kubernetes Cluster:**
* Cloud Provider: other
* Kubernetes Version: 1.23

**Anything else we need to know?**

**Comment by alexandradragodan** [comment]
Hey, @atovstonog! 👋 

Thanks for raising this up. 
Give us some time to reproduce it and we'll be back with updates. 

Appreciate your patience,
See you around! 💯

**Comment by atovstonog** [comment]
@FabianKramm this issue come back again )
