### ISSUE TITLE
Expressions in variable using "$1" do not resolve correctly

### ISSUE THREAD

**Issue by Quasarman** [loft-sh/devspace#2478]
**What happened?**

I am trying to put the expression `$( [ $1 == "dev" ] && echo "true" || echo "false" )` inside a variable to use the result in various places in my config. But it does not seem to correctly resolve the "$1" since the expression always results to `false` regardless if calling `devspace dev` or not.

**What did you expect to happen instead?**

I expect the variable to be resolved correctly.

**How can we reproduce the bug?** (as minimally and precisely as possible)

1. Put the following inside your devspace config

```
vars:
  TEST_VAR_EXPRESSION: $( [ $1 == "print" ] && echo "true" || echo "false" )
```

1. Call `devspace print`
2. Inspect that the variable is `false`

You can also change the `$1 == "print"` to any string really it will always return false.

My devspace.yaml:

```
version: v2beta1

vars:
  DEV_MODE: $( [ $1 == "dev" ] && echo "true" || echo "false" )

...
deployments:
  my-deployment:
      helm:
        chart:
          name: my/chart
        values:
          debug: ${DEV_MODE}
...
```

**Local Environment:**

* DevSpace Version: 6.2.2
* Operating System: windows
* ARCH of the OS: AMD64
  **Kubernetes Cluster:**
* Cloud Provider: other
* Kubernetes Version:
  * Client Version: v1.25.0
  * Kustomize Version: v4.5.7
  * Server Version: v1.24.2

**Anything else we need to know?**

Nope.

**Comment by FabianKramm** [comment]
@Quasarman thanks a lot for the PR! We'll try to reproduce this and create a fix as soon as possible.
