### ISSUE TITLE
`devspace upgrade --version v5.18.5` fails with `couldn't be found` error

### ISSUE THREAD

**Issue by JamesHutchisonCarta** [loft-sh/devspace#2489]
**What happened?**
Running the command `devspace upgrade --version v5.18.5` gives the error `fatal Couldn't upgrade: devspace version v5.18.5 couldn't be found`

**What did you expect to happen instead?**
Devspace downgrades to v5.18.5

**How can we reproduce the bug?** (as minimally and precisely as possible)

Run the command

Tested with Mac OS and a linux container and seeing the issue in both.

**Comment by FabianKramm** [comment]
Hello @JamesHutchisonCarta, thanks for creating this issue! Seems to be a problem in the underlying library we use that is only checking the latest page of releases. I've created a PR that resolves the problem, however this will only take effect for newer DevSpace versions then.
