### ISSUE TITLE
Init: add flag/detect to init from docker-compose file

### ISSUE THREAD

**Issue by FabianKramm** [loft-sh/devspace#386]
Would be nice if devspace could convert a docker compose file via kompose to a devspace, which would help people to adopt devspace if they already use docker compose.

**Comment by madhavajay** [comment]
Is this officially supported yet? I have rewritten our stack in `devspace.yaml` but im thinking of moving our dev stack to `k3d` on Docker Engine as a kind of half way to full kubernetes, but I don't know if I want to sunset our docker compose support. In a perfect world `devspace` would deploy to both Kubernetes and Compose using a single `devspace` file which would be cool.

**Comment by madhavajay** [comment]
@lizardruss no worries. We can close this for now.
