### ISSUE TITLE
Empty dependency tasks are possible

### ISSUE THREAD

**Issue by FlorianKutz** [loft-sh/devspace#653]
**What happened?**
I tested the resolver with an empty dependency task. It resolved to an empty dependency

**What did you expect to happen instead?**
Fitting error

**How can we reproduce the bug?** (as minimally and precisely as possible)
resolver.Resolve(\[\]\*latest.DependencyConfig{
&latest.DependencyConfig{
Source: &latest.SourceConfig{},
},
}, testCase.updateParam)

**Local Environment:**

* Operating System: windows

/kind bug

**Comment by LukasGentele** [comment]
@1522784 is this still an issue in v4?

**Comment by LukasGentele** [comment]
@1522784
