### ISSUE TITLE
tests: refactor cmd package for better testing

### ISSUE THREAD

**Issue by FabianKramm** [loft-sh/devspace#795]
Currently it is very hard to test the cmd package, because each client has to be overriden globally in the test and the working dir has to be switched. 

I would suggest we implement a client factory that will be passed to every command that will create the needed clients instead. This factory can be replaced by a test factory that will create test clients during tests. This makes the tests easier to write, since we could have a single test factory that can be adjusted if needed in a test.

**Comment by carlmontanari** [comment]
Going to close this out due to being veryyyyy old and probably not all that relevant anymore!
