### ISSUE TITLE
Support ngrok

### ISSUE THREAD

**Issue by chasebolt** [loft-sh/devspace#819]
As a user, I would like to be able to publicly share my development app. It would be nice to run `devspace share` that would create a ngrok tunnel for the kube proxy forwarding. This is a similar flow to other services such as `valet share` and `lando share`.

/kind feature

**Comment by LukasGentele** [comment]
Are you working with a localhost cluster such as Docker Kubernetes or minikube?

**Comment by chasebolt** [comment]
I have a mix. Some clients are dead set on using minikube and sticking with local development, while others prefer the flexibility of using a remote cluster. Clients that use a remote cluster we can jump through some hoops and setup an ingress for them, but this also makes it more of a permanent setup. Keeping development not public by default is preferred.

**Comment by LukasGentele** [comment]
Makes sense. For the ones using remote clusters, you can suggest the command `devspace open` which creates ingresses on the fly. For local clusters, we could think about adding a command like you are suggesting. Thanks for suggesting this feature, @chasebolt.

Inlets might be a project that we could integrate for this purpose: https://github.com/inlets/inlets

@FabianKramm: What's your take on this?

**Comment by chasebolt** [comment]
Honestly, I forgot about `devspace open` as I am used to just using `devspace dev` when developing. Bringing inlets to `devspace open` would be rad @LukasGentele :+1:

**Comment by FabianKramm** [comment]
Yes sounds good, but I would rather make this an option in `devspace open` than a complete new command

**Comment by alexellis** [comment]
Hey folks, if you need help with inlets, feel free to ask

**Comment by LukasGentele** [comment]
Thanks, @alexellis! Appreciate you reaching out. inlets is a great project and I think it is a nice addition to `devspace open` (which only creates an ingress on-demand). Integrating inlets directly into devspace is probably not a top priority right now because I think users can leverage `commands` and `hooks` in devspace.yaml to run inlets commands as part of their devspace workflows. However, we should definitely add a docs page or a tutorial with ways to use inlets+devspace.

**Comment by alexellis** [comment]
No worries @LukasGentele 

If devspace has a built-in terminal, [feel free to try it out](https://docs.inlets.dev), it should just work.
